// @ts-nocheck
jQuery(async function () {
    'use strict';

    var extensionName = 'comfyui-public-api-button';
    var extensionFolderPath = '/scripts/extensions/third-party/' + extensionName;
    var endpointDiscoveryUrl = 'https://momo-draw-endpoint.1830488003.workers.dev/v1/endpoint';
    var endpointDiscoveryIntervalMs = 30000;
    // 固定域名。与公告 Worker 的 FIXED_DOMAINS 白名单保持一致，
    // 改动其中一边时另一边也要同步改（WORKER: endpoint-registry/worker.js）。
    var apiUrlWhitelist = ['draw.410847381.xyz'];
    var updaterRepoOwner = '1830488003';
    var updaterRepoName = 'comfyui-public-api-button';
    var storageKey = 'comfyui_public_api_button_settings';
    var autoGeneratedStorageKey = 'comfyui_public_api_button_auto_generated';
    // 720p 及以上为高清档：生成更慢，且按服务端规则消耗 2 次额度
    var allowedResolutions = ['512x768', '512x512', '768x512', '720x1280', '1280x720'];
    var highResolutions = ['720x1280', '1280x720'];
    var HIGH_RES_CREDIT_COST = 2;
    var allowedSteps = [4, 6, 8];
    var stylePresets = [
        { id: 'kpop-idol-concept', name: '韩国女团概念照', label: '韩国女团概念照', description: '真人女团回归概念照，强调妆造、棚拍灯光和商业海报质感。', promptTitle: '韩国女团真人回归概念摄影', prefix: '明确的真人时尚摄影，韩国女团成员般的年轻女性，精致舞台妆容，统一但各有区别的高定表演服装，自信镜头表现力', suffix: '专业摄影棚布光，亮泽皮肤与真实毛孔，商业杂志精修，回归预告海报构图，潮流背景装置和高级流行音乐视觉' },
        { id: 'douyin-fashion', name: '抖音爆款穿搭', label: '抖音爆款穿搭', description: '真人短视频穿搭封面，突出身材比例、手机构图和鲜明调色。', promptTitle: '抖音爆款真人穿搭短视频封面摄影', prefix: '明确的真人手机人像摄影，热门中文短视频穿搭博主，突出身材比例的时髦服装，自信自然动作，都市街道或商场场景', suffix: '竖屏短视频封面构图，显脸小的近广角视角，明亮补光，干净锐利画面，鲜明但不过度的调色，熟悉的抖音爆款穿搭观感' },
        { id: 'korean-clean-girl', name: '韩系清冷女友感', label: '韩系清冷女友感', description: '真人韩系生活人像，淡妆、低饱和穿搭和柔和窗边光。', promptTitle: '韩系清冷真人生活人像摄影', prefix: '明确的真人生活方式人像摄影，清冷自然的年轻女性，淡颜干净妆容，柔顺发型，米白灰低饱和服装，松弛安静的日常姿态', suffix: '柔和窗边漫射光，真实自然皮肤纹理，浅景深，克制奶油色调，韩国生活杂志与女友感照片构图' },
        { id: 'xiaohongshu-lifestyle', name: '小红书氛围感', label: '小红书氛围感', description: '真人精致生活照片，咖啡旅行场景、窗边光和笔记封面构图。', promptTitle: '小红书真人生活方式摄影', prefix: '明确的真人生活方式摄影，时髦年轻人物，精致咖啡店民宿或旅行地点，看似随意但好看的自然动作，丰富桌面和环境小物', suffix: '柔和窗边光，温暖通透调色，真实皮肤与食物材质，轻微浅景深，精心设计的日常感，小红书热门笔记封面构图' },
        { id: 'y2k-streetwear', name: '千禧辣妹街拍', label: '千禧辣妹街拍', description: '真人千禧辣妹街拍，直闪、低腰穿搭和夜间霓虹街景。', promptTitle: '千禧年辣妹真人街头时尚摄影', prefix: '明确的真人时尚街拍，千禧年辣妹造型，修身短上衣与低腰下装，金属首饰和亮面材质，自信俏皮姿态，夜间商业街背景', suffix: '相机直打闪光灯，轻微广角透视，霓虹招牌与车灯，亮泽杂志调色，世纪初流行文化和韩国街拍氛围' },
        { id: 'new-chinese-chic', name: '新中式穿搭', label: '新中式穿搭', description: '真人新中式时尚摄影，现代剪裁结合立领盘扣和东方面料。', promptTitle: '新中式真人时尚杂志摄影', prefix: '明确的真人时尚摄影，当代日常服装融入立领盘扣斜襟和东方提花面料，现代简洁剪裁，优雅自然姿态，中式现代建筑环境', suffix: '雅致米白墨黑黛青配色，柔和电影光线，真实丝绸与棉麻纹理，留白构图，高级中文时尚杂志质感' },
        { id: 'guochao-streetwear', name: '国潮街头', label: '国潮街头', description: '真人国潮广告，传统纹样结合街头廓形和中国城市背景。', promptTitle: '现代国潮真人街头广告摄影', prefix: '明确的真人潮流广告摄影，现代街头服装融合传统中式纹样与盘扣结构，宽松层叠廓形，年轻人物自信姿态，中国城市街区背景', suffix: '红黑金与水墨色点缀，硬朗商业灯光，低机位广角构图，清晰布料印花与鞋服细节，国产潮牌宣传大片质感' },
        { id: 'hanfu-cinematic', name: '汉服仙侠大片', label: '汉服仙侠大片', description: '真人古装影视剧照，真实演员、汉服材质和仙侠电影场景。', promptTitle: '真人汉服仙侠电影剧照', prefix: '明确的真人古装影视摄影，穿精致汉服的仙侠角色，真实演员五官与皮肤，复杂发髻和金玉发饰，飘动宽袖与多层衣摆，宏大中式幻想场景', suffix: '电影级布景与灯光，云雾体积光，真实丝绸刺绣纹理，武侠电影镜头构图，山川宫殿背景，真人影视海报质感' },
        { id: 'old-money-glamour', name: '千金老钱风', label: '千金老钱风', description: '真人低调奢华杂志大片，经典剪裁、庄园环境和奶油色调。', promptTitle: '千金老钱风真人奢华杂志摄影', prefix: '明确的真人高级时尚摄影，低调奢华的年轻女性，剪裁合体的经典服装，珍珠与皮革配饰，庄园酒店或高级会所环境', suffix: '柔和自然侧光，奶油棕色调，真实高级面料纹理，端庄克制姿态，国际奢侈品杂志大片构图' },
        { id: 'dopamine-fashion', name: '多巴胺穿搭', label: '多巴胺穿搭', description: '真人高饱和时尚广告，强调撞色服装和快乐活力。', promptTitle: '多巴胺真人商业时尚摄影', prefix: '明确的真人商业时尚摄影，高饱和撞色服装，多层次彩色配饰，快乐有活力的姿态，明亮简洁背景', suffix: '阳光充足，清晰商业广告构图，鲜艳但肤色自然的调色，服装颜色块层次分明，年轻社交媒体潮流感' },
        { id: 'phone-flash-candid', name: '手机闪光灯随拍', label: '手机闪光灯随拍', description: '真人手机直闪抓拍，轻微过曝、随手构图和夜生活氛围。', promptTitle: '真人手机直闪随拍摄影', prefix: '明确的真人手机快照，朋友视角的自然抓拍，人物动作松弛不摆拍，夜间餐厅街道卧室或聚会场景，正面手机闪光灯', suffix: '真实皮肤纹理，轻微过曝和运动模糊，不完全水平的随手取景，近距离广角感，朋友圈夜生活照片氛围' },
        { id: 'cosplay-realism', name: '高还原角色扮演写真', label: '高还原角色扮演写真', description: '真人高还原角色扮演写真，准确服装道具和电影级实景灯光。', promptTitle: '高还原游戏角色真人扮演摄影', prefix: '明确的真人角色扮演摄影，真人演员高度还原幻想游戏角色，准确的假发妆容服装武器和配饰，符合角色性格的姿态与表情', suffix: '真实布料皮革金属材质，电影感实景灯光，专业棚拍或外景构图，角色宣传海报级精修，同时保留真人皮肤质感' },
        { id: 'blindbox-3d', name: '潮玩盲盒三维', label: '潮玩盲盒三维', description: '明确三维潮玩商品渲染，大头小身体、搪胶材质和影棚陈列。', promptTitle: '潮玩盲盒三维商品渲染', prefix: '明确的三维潮玩商品建模，圆润迷你人物比例，大头小身体，简化可爱五官，精致微型服装和配件，收藏级设计师玩具造型', suffix: '光滑搪胶与树脂材质，干净影棚三点布光，柔和接触阴影，彩色商品陈列台，商业盲盒包装宣传图和清晰三维渲染质感' },
        { id: 'genshin-open-world', name: '原神感三维游戏', label: '原神感三维游戏', description: '原神式三维开放世界游戏画面，卡通建模、赛璐璐渲染、元素特效和明亮幻想场景。', promptTitle: '原神风格的三维开放世界游戏官方宣传画面', prefix: '整张图必须呈现为原神式日系幻想开放世界游戏的三维实时渲染画面，而不是真人摄影，也不是二维平面插画。角色使用精致的三维卡通建模，日式二次元脸型、大眼睛、清晰的三维发束、层次丰富的幻想服装模型与饰品，身体比例自然灵动，姿势像游戏角色技能演出或剧情过场', suffix: '采用高质量游戏引擎赛璐璐渲染，角色轮廓有柔和描边与受光分区，皮肤保持光滑的卡通三维材质，头发和衣料有明确模型结构。环境是色彩明亮的开放世界幻想大陆，包含山川、遗迹、天空与元素粒子，加入风、火、水、雷等元素光效、体积光、景深和电影式运镜构图，最终效果必须像官方三维游戏截图和角色宣传PV，不要写实真人皮肤，不要照片感' },
        { id: 'arknights-tactical', name: '明日方舟感战术插画', label: '明日方舟感战术插画', description: '明日方舟式二维战术宣传图，工业末世都市、机能服装、冷色设计和克制角色气质。', promptTitle: '明日方舟风格的二维战术角色宣传插画', prefix: '整张图必须是明日方舟式高完成度二维商业插画，而不是真人照片或三维人物。角色采用修长利落的二次元比例、冷静克制的表情、清晰锐利的脸部与发丝设计，穿多层战术机能服、制服、束带、护具、通讯设备和工业化配件，服装结构复杂但阅读清楚', suffix: '背景使用灾后工业都市、移动设施、警示标识、混凝土、金属结构和薄雾，整体以灰黑、冷蓝、米白为主，少量红色或黄色作视觉警示。使用干净线稿、细腻赛璐璐与轻厚涂结合、锐利轮廓光、平面设计切割、局部文字留白和非对称海报构图，最终效果像高端二次元战术手游角色立绘与活动主视觉，不要真人化，不要普通日漫校园感' },
        { id: 'gacha-character-splash', name: '热门二游角色立绘', label: '热门二游角色立绘', description: '高完成度二维抽卡角色立绘，全身角色、华丽服装、动态姿态和环绕式技能特效。', promptTitle: '热门二次元手游的二维抽卡角色立绘', prefix: '整张图必须是精致的二维商业游戏角色插画，而不是真人摄影或三维建模。角色以完整全身或接近全身的英雄姿态成为绝对主体，具有漂亮清晰的动漫五官、层次丰富的发丝、独特剪影、华丽且有功能逻辑的服装、武器与配饰，动作有张力并能体现角色职业和性格', suffix: '使用高质量赛璐璐上色与细腻数字厚涂融合，轮廓清楚，材质区分明确，金属、布料、皮革、宝石分别呈现。角色周围展开大面积技能轨迹、元素粒子、能量光带、碎片和象征性图案，采用斜向动势、前后景遮挡和卡池宣传图构图，背景服务于角色而不过分抢眼，最终效果像热门二游五星角色立绘和版本主视觉，不要真人脸，不要摄影光圈效果' },
        { id: 'donghua-3d-character', name: '国漫三维角色', label: '国漫三维角色', description: '国漫电影级三维角色，东方半写实五官、精细发丝、仙侠服饰和电影灯光。', promptTitle: '中国仙侠国漫电影级三维角色渲染', prefix: '整张图必须呈现为中国仙侠国漫的电影级三维动画画面，而不是真人照片或二维插画。角色采用东方审美的半写实三维脸型，精致但明显经过动画设计的五官，细密可见的三维发丝与发饰，穿多层飘逸仙侠服装，包含丝绸、纱、刺绣、玉石、金属和皮革材质，姿态优雅有力量感', suffix: '采用电影级三维动画渲染，皮肤有克制的次表面散射，眼睛有动画角色的通透高光，发丝、衣料和首饰具有清晰的物理材质。加入云海、山门、古殿、灵气、剑光和体积雾，使用东方电影构图、冷暖交错光线、浅景深和宏大环境纵深，最终效果像高预算国漫电影剧照与官方角色海报，不要变成真人古装写真' },
        { id: 'korean-webtoon', name: '韩漫恋爱感', label: '韩漫恋爱感', description: '现代恋爱韩漫封面，修长人物、精致线稿、柔和渐变和明显的情感互动。', promptTitle: '现代都市恋爱韩漫的二维封面插画', prefix: '整张图必须是现代韩国恋爱条漫的二维数字插画，而不是真人照片。人物具有修长漂亮的身材比例、精致小巧的脸型、清晰五官、光滑细致的发丝和时髦都市服装；多人场景必须通过靠近、对视、牵手、拥抱或保护姿态表现明确的感情关系，人物动作自然，像韩漫关键分镜', suffix: '采用干净细线稿、柔和的赛璐璐渐变上色、通透肤色、发丝高光与细腻眼神，背景适度简化但保留咖啡店、办公室、公寓、夜景街道等现代都市信息。使用浪漫逆光、花瓣或光斑、电影分镜式裁切和封面构图，最终效果像高人气恋爱韩漫彩色封面，不要真实皮肤毛孔，不要摄影写实感' },
        { id: 'cinematic-photo', name: 'Cinematic Photo', promptTitle: '电影感摄影风格', prefix: '电影感照片，自然光照', suffix: '高反差，专业摄影质感，清晰对焦，浅景深' },
        { id: 'medium-format', name: 'Medium Format', promptTitle: '中画幅胶片风格', prefix: '中画幅胶片照片，电影剧照氛围', suffix: '电影轮廓光，柔和胶片颗粒，柯达波特拉色调' },
        { id: 'analog-film', name: 'Analog Film', promptTitle: '复古模拟胶片风格', prefix: '模拟胶片照片，颗粒纹理，暖色偏移，轻微暗角', suffix: '复古胶片质感，细腻颗粒，褪色高光，柔和阴影' },
        { id: 'point-and-shoot-candid', name: 'Point-and-Shoot Candid', promptTitle: '随手抓拍风格', prefix: '便携相机自然抓拍，手持拍摄的不完美感', suffix: '轻微运动柔化，机顶闪光灯衰减，未经摆拍的纪实感' },
        { id: 'ansel-adams-landscape', name: 'Ansel Adams Landscape', promptTitle: '亚当斯黑白风景风格', prefix: '高反差大画幅黑白风景，强烈明暗层次', suffix: '区域曝光，锐利前景细节，永恒黑白质感，细腻颗粒写实' },
        { id: 'film-noir', name: 'Film Noir', promptTitle: '黑色电影风格', prefix: '黑色电影美学，黑白色调，强烈反差，阴郁方向性阴影', suffix: '二十世纪四十年代氛围，神秘电影光线，深黑层次' },
        { id: 'neon-noir', name: 'Neon Noir', promptTitle: '霓虹黑色电影风格', prefix: '霓虹黑色电影，雨夜街道，赛博未来气息', suffix: '发光招牌，高反差，低照度，积水反射' },
        { id: 'cyberpunk', name: 'Cyberpunk', promptTitle: '赛博朋克风格', prefix: '霓虹笼罩的赛博未来，密集全息影像，雨夜街道', suffix: '发光电子线路，反光表面，强烈电气氛围' },
        { id: 'solarpunk', name: 'Solarpunk', promptTitle: '太阳朋克风格', prefix: '明亮太阳朋克乌托邦，有机建筑，繁茂绿植与科技融合', suffix: '阳光照耀的可再生能源系统，和谐生态设计，柔和乐观色调' },
        { id: 'dieselpunk', name: 'Dieselpunk', promptTitle: '柴油朋克风格', prefix: '柴油朋克复古工业美学，厚重的二十世纪三十年代机械', suffix: '粗粝油污纹理，黄铜配件，烟雾弥漫' },
        { id: 'steampunk', name: 'Steampunk', promptTitle: '蒸汽朋克风格', prefix: '蒸汽朋克美学，黄铜机械，维多利亚工业氛围', suffix: '齿轮，铆钉，暖色古董金属色调，繁复细节' },
        { id: 'epic-concept-art', name: 'Epic Concept Art', promptTitle: '史诗概念艺术风格', prefix: '电影级大型游戏概念艺术，辽阔景观，细致建筑结构', suffix: '英雄式构图，大气纵深，极度精致的商业渲染' },
        { id: 'ethereal-fantasy', name: 'Ethereal Fantasy', promptTitle: '空灵幻想风格', prefix: '空灵幻想概念艺术', suffix: '宏伟，圣洁，绘画感，史诗，庄严，梦幻封面艺术' },
        { id: 'dark-fantasy-painterly', name: 'Dark Fantasy Painterly', promptTitle: '暗黑幻想绘画风格', prefix: '暗黑高级幻想数字绘画，压抑深沉氛围', suffix: '戏剧性阴影，神秘光线，细腻丰富的环境绘制' },
        { id: 'ghibli-inspired', name: 'Ghibli-Inspired', promptTitle: '吉卜力动画风格', prefix: '吉卜力感手绘二维动画，温柔奇幻的日式动画电影美学，简洁生动的动漫人物设计', suffix: '赛璐璐手绘背景，干净动漫五官，柔和绘画光线，温暖配色，繁茂环境细节，明确的非写实插画' },
        { id: 'dark-moebius', name: 'Dark Moebius', promptTitle: '暗黑莫比乌斯幻想风格', prefix: '图像化超现实幻想，锐利线条，梦境般建筑', suffix: '有限色板，棱角构图，诡异紧张的空气感' },
        { id: 'comic-book', name: 'Comic Book', promptTitle: '美式漫画风格', prefix: '西方漫画风格，强烈墨线轮廓，大胆平面图形', suffix: '网点阴影，鲜明纯色，动感英雄式构图' },
        { id: 'manga', name: 'Manga', promptTitle: '黑白漫画风格', prefix: '黑白漫画插画，强烈勾线，分镜式反差', suffix: '网点纸阴影，风格化表情，动感速度线' },
        { id: 'anime-key-visual', name: 'Anime Key Visual', promptTitle: '动漫主视觉风格', prefix: '动画作品主视觉，专业动画海报', suffix: '鲜艳色彩，高细节赛璐璐上色，情绪化构图' },
        { id: '90s-ova-anime', name: '90s OVA Anime', promptTitle: '二十世纪九十年代动画录像带风格', prefix: '二十世纪九十年代动画录像带美学，清晰赛璐璐轮廓，复古配色', suffix: '胶片颗粒纹理，戏剧性高光，怀旧阴影' },
        { id: 'pixel-art', name: 'Pixel Art', promptTitle: '像素画风格', prefix: '复古像素插画，清晰像素网格', suffix: '有限色板，十六位游戏美学，怀旧电子游戏风格' },
        { id: 'watercolor', name: 'Watercolor', promptTitle: '水彩画风格', prefix: '水彩绘画，松散笔触，颜料自然晕染', suffix: '鲜艳，绘画感，丰富肌理，柔和纸张纹理' },
        { id: 'stained-glass', name: 'Stained Glass', promptTitle: '彩色玻璃风格', prefix: '彩色玻璃美学，铅条轮廓，半透明色块', suffix: '鲜艳背光，繁复细节，教堂花窗氛围' },
        { id: 'art-deco', name: 'Art Deco', promptTitle: '装饰艺术风格', prefix: '装饰艺术美学，几何形状，大胆对称', suffix: '奢华金色点缀，华丽装饰细节' },
        { id: 'tilt-shift', name: 'Tilt Shift', promptTitle: '移轴微缩摄影风格', prefix: '移轴摄影，选择性对焦，微缩模型效果', suffix: '背景虚化，鲜艳饱和度，玩具场景观感' }
    ];
    var stylePresetUi = {
        'genshin-open-world': { label: '原神感三维游戏', group: '🔥 热门动漫与游戏', description: '纯提示词生成：三维开放世界游戏建模、赛璐璐渲染、元素特效和明亮幻想场景。' },
        'arknights-tactical': { label: '明日方舟感战术插画', group: '🔥 热门动漫与游戏', description: '纯提示词生成：二维战术宣传图、工业末世都市、机能服装和克制冷色设计。' },
        'gacha-character-splash': { label: '热门二游角色立绘', group: '🔥 热门动漫与游戏', description: '纯提示词生成：二维抽卡角色立绘、华丽服装、动态姿态和环绕式技能特效。' },
        'donghua-3d-character': { label: '国漫三维角色', group: '🔥 热门动漫与游戏', description: '纯提示词生成：电影级三维国漫人物、东方半写实五官、仙侠材质和体积光。' },
        'kpop-idol-concept': { label: '韩国女团概念照', group: '🔥 热门写真与设计', description: '真人女团回归概念照，强调妆造、棚拍灯光和商业海报质感。' },
        'korean-clean-girl': { label: '韩系清冷女友感', group: '🔥 热门写真与设计', description: '真人韩系生活人像，淡妆、低饱和穿搭和柔和窗边光。' },
        'douyin-fashion': { label: '抖音爆款穿搭', group: '🔥 热门写真与设计', description: '真人短视频穿搭封面，突出身材比例、手机构图和鲜明调色。' },
        'y2k-streetwear': { label: '千禧辣妹街拍', group: '🔥 热门写真与设计', description: '真人千禧辣妹街拍，直闪、低腰穿搭和夜间霓虹街景。' },
        'dopamine-fashion': { label: '多巴胺穿搭', group: '🔥 热门写真与设计', description: '真人高饱和时尚广告，强调撞色服装和快乐活力。' },
        'old-money-glamour': { label: '千金老钱风', group: '🔥 热门写真与设计', description: '真人低调奢华杂志大片，经典剪裁、庄园环境和奶油色调。' },
        'guochao-streetwear': { label: '国潮街头', group: '🔥 热门写真与设计', description: '真人国潮广告，传统纹样结合街头廓形和中国城市背景。' },
        'new-chinese-chic': { label: '新中式穿搭', group: '🔥 热门写真与设计', description: '真人新中式时尚摄影，现代剪裁结合立领盘扣和东方面料。' },
        'hanfu-cinematic': { label: '汉服仙侠大片', group: '🔥 热门写真与设计', description: '真人古装影视剧照，真实演员、汉服材质和仙侠电影场景。' },
        'xiaohongshu-lifestyle': { label: '小红书氛围感', group: '🔥 热门写真与设计', description: '真人精致生活照片，咖啡旅行场景、窗边光和笔记封面构图。' },
        'phone-flash-candid': { label: '手机闪光灯随拍', group: '🔥 热门写真与设计', description: '真人手机直闪抓拍，轻微过曝、随手构图和夜生活氛围。' },
        'korean-webtoon': { label: '韩漫恋爱感', group: '🔥 热门动漫与游戏', description: '纯提示词生成：现代都市恋爱韩漫封面，修长人物、精致线稿和浪漫互动。' },
        'cosplay-realism': { label: '高还原角色扮演写真', group: '🔥 热门写真与设计', description: '真人高还原角色扮演写真，准确服装道具和电影级实景灯光。' },
        'blindbox-3d': { label: '潮玩盲盒三维', group: '🔥 热门写真与设计', description: '明确三维潮玩商品渲染，大头小身体、搪胶材质和影棚陈列。' },
        'cinematic-photo': { label: '电影感摄影', group: '摄影写实', description: '自然光、强对比、专业摄影质感和浅景深。' },
        'medium-format': { label: '中画幅胶片', group: '摄影写实', description: '电影剧照般的中画幅胶片质感，柔和颗粒和柯达色调。' },
        'analog-film': { label: '复古模拟胶片', group: '摄影写实', description: '温暖偏色、轻微暗角、褪色高光和复古胶片颗粒。' },
        'point-and-shoot-candid': { label: '随手抓拍', group: '摄影写实', description: '手持相机的自然抓拍感，轻微运动模糊和闪光灯效果。' },
        'ansel-adams-landscape': { label: '亚当斯黑白风景', group: '摄影写实', description: '高反差大画幅黑白风景，前景锐利、层次丰富。' },
        'film-noir': { label: '黑色电影', group: '摄影写实', description: '1940年代黑白电影氛围，深黑阴影和神秘方向光。' },
        'tilt-shift': { label: '移轴微缩摄影', group: '摄影写实', description: '选择性对焦和微缩模型效果，色彩鲜明、背景虚化。' },
        'neon-noir': { label: '霓虹黑色电影', group: '科幻与复古未来', description: '雨夜街道、霓虹招牌、低光高反差和湿地反射。' },
        'cyberpunk': { label: '赛博朋克', group: '科幻与复古未来', description: '密集霓虹、全息影像、电子线路和未来都市氛围。' },
        'solarpunk': { label: '太阳朋克', group: '科幻与复古未来', description: '绿色植物与科技共生的明亮未来，环保、温暖、乐观。' },
        'dieselpunk': { label: '柴油朋克', group: '科幻与复古未来', description: '1930年代重工业机械、油污纹理、黄铜和烟雾。' },
        'steampunk': { label: '蒸汽朋克', group: '科幻与复古未来', description: '维多利亚工业风、齿轮铆钉和暖色古铜机械。' },
        'art-deco': { label: '装饰艺术', group: '科幻与复古未来', description: '几何造型、强烈对称和华丽金色装饰。' },
        'epic-concept-art': { label: '史诗概念设计', group: '幻想与概念艺术', description: '宏大场景、英雄构图、空间纵深和游戏概念设计质感。' },
        'ethereal-fantasy': { label: '空灵幻想', group: '幻想与概念艺术', description: '梦幻、神圣、宏伟的绘画感幻想封面风格。' },
        'dark-fantasy-painterly': { label: '暗黑幻想绘画', group: '幻想与概念艺术', description: '阴郁的高幻想氛围、戏剧阴影和神秘光线。' },
        'ghibli-inspired': { label: '吉卜力灵感', group: '幻想与概念艺术', description: '温暖手绘故事感、柔和光线和茂盛环境细节。' },
        'dark-moebius': { label: '暗黑莫比乌斯', group: '幻想与概念艺术', description: '超现实建筑、硬朗线条、有限色彩和诡异梦境感。' },
        'anime-key-visual': { label: '动漫主视觉', group: '动漫与漫画', description: '鲜艳细致的动画主视觉，赛璐璐上色和情绪化构图。' },
        '90s-ova-anime': { label: '90年代OVA动漫', group: '动漫与漫画', description: '复古动画配色、清晰赛璐璐轮廓和怀旧胶片颗粒。' },
        'manga': { label: '日式黑白漫画', group: '动漫与漫画', description: '黑白墨线、网点阴影、夸张表情和动态速度线。' },
        'comic-book': { label: '美式漫画', group: '动漫与漫画', description: '粗壮墨线、鲜明平涂、网点阴影和英雄式构图。' },
        'pixel-art': { label: '像素艺术', group: '艺术与特殊效果', description: '清晰像素格、有限色板和16位复古游戏质感。' },
        'watercolor': { label: '水彩画', group: '艺术与特殊效果', description: '松散笔触、颜料晕染、鲜活色彩和纸张纹理。' },
        'stained-glass': { label: '彩色玻璃', group: '艺术与特殊效果', description: '铅条分割、半透明色块和教堂窗户般的背光。' }
    };
    var defaultSettings = {
        apiUrl: 'https://draw.410847381.xyz',
        apiKey: '',
        installId: '',
        resolution: '768x512',
        steps: 4,
        autoGenerate: false,
        stylePreset: 'anime-key-visual'
    };
    var contextGetter = function () {
        return window.SillyTavern && window.SillyTavern.getContext
            ? window.SillyTavern.getContext()
            : null;
    };
    var extensionSettingsRoot = window.extension_settings || {};
    extensionSettingsRoot[extensionName] = extensionSettingsRoot[extensionName] || {};
    var lastQueueAhead = 0;
    var lastKnownQuota = null;
    var queueState = 'offline';
    var queuePollBusy = false;
    var trialClaimPromise = null;
    var purchaseNoticeShown = false;
    var endpointDiscoveryPromise = null;
    var lastEndpointDiscoveryAt = 0;
    var autoGenerateTimer = null;
    var autoGeneratePollingBusy = false;
    var autoGenerateInFlight = new Set();
    var autoGenerateRetryAfter = new Map();
    var updaterState = {
        currentVersion: '0.0.0',
        latestVersion: '0.0.0',
        available: false,
        checking: false,
        updating: false,
        notifiedVersion: ''
    };

    function loadLocalSettings() {
        try {
            return JSON.parse(localStorage.getItem(storageKey) || '{}') || {};
        } catch (error) {
            console.warn('[' + extensionName + '] settings parse failed', error);
            return {};
        }
    }

    function normalizeSteps(value) {
        var numeric = Number(value);
        return allowedSteps.indexOf(numeric) >= 0 ? numeric : defaultSettings.steps;
    }

    function normalizeResolution(value) {
        var text = String(value || '');
        return allowedResolutions.indexOf(text) >= 0 ? text : defaultSettings.resolution;
    }

    function getStylePreset(value) {
        var presetId = String(value || '');
        return stylePresets.find(function (preset) { return preset.id === presetId; })
            || stylePresets.find(function (preset) { return preset.id === defaultSettings.stylePreset; })
            || stylePresets[0];
    }

    function normalizeStylePreset(value) {
        return getStylePreset(value).id;
    }

    function getStylePresetUi(value) {
        var preset = getStylePreset(value);
        return stylePresetUi[preset.id] || { label: preset.name, group: '其他', description: '插件将自动补充对应的画风和质量提示词。' };
    }

    function buildStyledPrompt(scenePrompt, presetId) {
        var preset = getStylePreset(presetId);
        var presetUi = stylePresetUi[preset.id] || {};
        var promptTitle = String(preset.promptTitle || presetUi.label || preset.name).trim();
        var sceneText = String(scenePrompt || '').trim();
        return [
            promptTitle + '。',
            String(preset.prefix || '').trim() + '。',
            '画面主体与场景内容：' + sceneText + '。',
            String(preset.suffix || '').trim() + '。'
        ].filter(Boolean).join('');
    }

    // 一次性迁移：固定域名上线后，用户 localStorage 里可能还存着已失效的旧
    // trycloudflare 地址（老版本写死的默认值）。
    //
    // 注意：旧地址的「格式」本身仍符合 trycloudflare 规则，会被 isAllowedApiUrl 放行，
    // 所以不能只靠白名单判断，必须显式列出这些已知死地址。
    // 地址发现虽然会在启动时强制刷新，但万一公告接口当时不可用，就会一直沿用死地址
    // 并报「无法连接服务器」。清掉后回落成 defaultSettings.apiUrl（固定域名），保证能恢复。
    var legacyDeadApiUrls = [
        'https://magic-arthritis-maintain-altered.trycloudflare.com'
    ];
    var apiUrlMigrated = false;
    try {
        var migrateStore = JSON.parse(localStorage.getItem(storageKey) || '{}') || {};
        var storedUrl = normalizeApiUrl(migrateStore.apiUrl);
        var isDeadLegacy = storedUrl && legacyDeadApiUrls.some(function (dead) {
            return normalizeApiUrl(dead).toLowerCase() === storedUrl.toLowerCase();
        });
        if (storedUrl && (isDeadLegacy || !isAllowedApiUrl(storedUrl))) {
            console.warn('[' + extensionName + '] 清除失效的旧服务器地址：', migrateStore.apiUrl);
            delete migrateStore.apiUrl;
            localStorage.setItem(storageKey, JSON.stringify(migrateStore));
            apiUrlMigrated = true;
        }
    } catch (error) {
        console.warn('[' + extensionName + '] 旧地址迁移失败', error);
    }
    if (apiUrlMigrated && extensionSettingsRoot[extensionName]) {
        delete extensionSettingsRoot[extensionName].apiUrl;
    }

    var settings = Object.assign({}, defaultSettings, loadLocalSettings(), extensionSettingsRoot[extensionName]);
    settings.resolution = normalizeResolution(settings.resolution);
    settings.steps = normalizeSteps(settings.steps);
    settings.autoGenerate = Boolean(settings.autoGenerate);
    settings.stylePreset = normalizeStylePreset(settings.stylePreset);
    Object.assign(extensionSettingsRoot[extensionName], settings);

    function loadAutoGeneratedMap() {
        try {
            return JSON.parse(localStorage.getItem(autoGeneratedStorageKey) || '{}') || {};
        } catch (error) {
            console.warn('[' + extensionName + '] auto generation record parse failed', error);
            return {};
        }
    }

    function saveAutoGeneratedMap(map) {
        try {
            localStorage.setItem(autoGeneratedStorageKey, JSON.stringify(map || {}));
        } catch (error) {
            console.warn('[' + extensionName + '] auto generation record save failed', error);
        }
    }

    function getChatKey() {
        var context = contextGetter();
        return String(
            (context && (context.chatId || context.groupId || context.name2 || context.characterName))
            || 'unknown_chat'
        );
    }

    function getLastAiMessageIndex() {
        var context = contextGetter();
        var chat = context && Array.isArray(context.chat) ? context.chat : [];
        for (var index = chat.length - 1; index >= 0; index--) {
            if (chat[index] && !chat[index].is_user) return index;
        }
        return null;
    }

    function markMessageGenerated(messageId, prompt) {
        var chatKey = getChatKey();
        var map = loadAutoGeneratedMap();
        map[chatKey] = map[chatKey] || {};
        map[chatKey][String(messageId)] = prompt;
        saveAutoGeneratedMap(map);
    }

    function scheduleAutoGenerate(reason) {
        if (!settings.autoGenerate || !settings.apiKey) return;
        if (autoGenerateTimer) clearTimeout(autoGenerateTimer);
        autoGenerateTimer = setTimeout(function () {
            checkAutoGenerate(reason || '').catch(function (error) {
                console.warn('[' + extensionName + '] auto generation failed', error);
            });
        }, 1200);
    }

    async function checkAutoGenerate(reason) {
        if (!settings.autoGenerate || !settings.apiKey || autoGeneratePollingBusy) return;
        autoGeneratePollingBusy = true;
        try {
            var context = contextGetter();
            var chat = context && Array.isArray(context.chat) ? context.chat : [];
            var messageId = getLastAiMessageIndex();
            if (typeof messageId !== 'number') return;
            var message = chat[messageId];
            if (!message || message.is_user) return;

            var prompt;
            try {
                prompt = extractImagePrompt(message.mes);
            } catch (error) {
                return;
            }

            var chatKey = getChatKey();
            var map = loadAutoGeneratedMap();
            var previousPrompt = (message.extra && message.extra.cpab_auto_generated_prompt)
                || (map[chatKey] && map[chatKey][String(messageId)]);
            if (previousPrompt === prompt) return;

            var inFlightKey = chatKey + '::' + messageId + '::' + prompt;
            if (autoGenerateInFlight.has(inFlightKey)) return;
            if (Number(autoGenerateRetryAfter.get(inFlightKey) || 0) > Date.now()) return;

            autoGenerateInFlight.add(inFlightKey);
            try {
                ensureButtonForMessage(messageId);
                var $button = $('.cpab-mes-button[data-cpab-mesid="' + messageId + '"]').first();
                setStatus('检测到新楼层绘画提示词，正在自动生图...');
                await generateForMessage(messageId, $button.length ? $button : null, 'normal');
                autoGenerateRetryAfter.delete(inFlightKey);
            } catch (error) {
                autoGenerateRetryAfter.set(inFlightKey, Date.now() + 15000);
                setStatus('自动生图失败，15秒后重试：' + (error.message || error));
                if (Number(error.status) === 402 || /次数已用完|卡密已过期/.test(String(error.message || ''))) {
                    showPurchaseNotice(true);
                }
                console.warn('[' + extensionName + '] automatic generation error (' + (reason || 'poll') + ')', error);
            } finally {
                autoGenerateInFlight.delete(inFlightKey);
            }
        } finally {
            autoGeneratePollingBusy = false;
        }
    }

    function showToast(type, message) {
        if (window.toastr && window.toastr[type]) {
            window.toastr[type](message, '默默画图');
        } else {
            console[type === 'error' ? 'error' : 'log'](message);
        }
    }

    function parseManifestVersion(content) {
        try {
            return String(JSON.parse(content).version || '0.0.0').trim();
        } catch (error) {
            throw new Error('版本文件格式错误');
        }
    }

    function compareVersions(left, right) {
        var leftParts = String(left || '0.0.0').replace(/^v/i, '').split('.').map(Number);
        var rightParts = String(right || '0.0.0').replace(/^v/i, '').split('.').map(Number);
        var length = Math.max(leftParts.length, rightParts.length);
        for (var index = 0; index < length; index++) {
            var leftValue = Number.isFinite(leftParts[index]) ? leftParts[index] : 0;
            var rightValue = Number.isFinite(rightParts[index]) ? rightParts[index] : 0;
            if (leftValue > rightValue) return 1;
            if (leftValue < rightValue) return -1;
        }
        return 0;
    }

    /* 从多个源读取版本文件，取版本号最高的那个。
       为什么要多个源：GitHub 的 raw CDN 会按 URL 路径缓存，推送新版本后
       .../main/manifest.json 可能长时间仍返回旧内容（实测遇到过一直返回上一个
       版本、X-Cache: HIT 的情况），导致「检查更新」永远发现不了新版本。
       /refs/heads/main/ 与 jsDelivr 走的是不同的缓存，通常能立刻拿到最新内容。
       任何一个源成功即可，全部失败才报错。 */
    function updaterSources(filePath) {
        var repo = updaterRepoOwner + '/' + updaterRepoName;
        var bust = '?t=' + Date.now();
        return [
            'https://raw.githubusercontent.com/' + repo + '/refs/heads/main/' + filePath + bust,
            'https://cdn.jsdelivr.net/gh/' + repo + '@main/' + filePath + bust,
            'https://raw.githubusercontent.com/' + repo + '/main/' + filePath + bust
        ];
    }

    async function fetchRemoteUpdaterFile(filePath) {
        var sources = updaterSources(filePath);
        var lastError = null;
        /* 按可靠性顺序试，第一个能用的就采用。
           /refs/heads/main/ 走的是与 /main/ 不同的缓存，实测能立刻拿到刚推送的版本。 */
        for (var i = 0; i < sources.length; i++) {
            try {
                var response = await fetch(sources[i], { cache: 'no-store' });
                if (!response.ok) { lastError = new Error('HTTP ' + response.status); continue; }
                var content = await response.text();
                if (parseManifestVersion(content)) { return content; }
                lastError = new Error('版本文件内容不合法');
            } catch (error) {
                lastError = error;
            }
        }
        throw lastError || new Error('无法读取版本文件，请检查网络');
    }

    function renderUpdateState(message) {
        $('#cpab-current-version').text(updaterState.currentVersion);
        $('#cpab-update-status').text(message || '');
        $('#cpab-settings .cpab-update-panel').toggleClass('has-update', updaterState.available);
        var $button = $('#cpab-check-update');
        if (updaterState.updating) {
            $button.prop('disabled', true).html('<i class="fa-solid fa-spinner fa-spin"></i> 正在更新...');
        } else if (updaterState.checking) {
            $button.prop('disabled', true).html('<i class="fa-solid fa-spinner fa-spin"></i> 检查中...');
        } else if (updaterState.available) {
            $button.prop('disabled', false).html('<i class="fa-solid fa-cloud-arrow-down"></i> 立即更新 v' + updaterState.latestVersion);
        } else {
            $button.prop('disabled', false).html('<i class="fa-solid fa-cloud-arrow-down"></i> 检查更新');
        }
    }

    function showAutomaticUpdateNotice() {
        if (!updaterState.available || updaterState.notifiedVersion === updaterState.latestVersion) return;
        updaterState.notifiedVersion = updaterState.latestVersion;
        var message = '发现新版本 v' + updaterState.latestVersion + '，请打开“默默画图”设置，点击“立即更新”。';
        if (window.toastr && window.toastr.warning) {
            window.toastr.warning(message, '默默画图有更新', {
                closeButton: true,
                timeOut: 0,
                extendedTimeOut: 0
            });
        } else {
            window.alert(message);
        }
    }

    async function checkForUpdates(isManual) {
        if (updaterState.checking || updaterState.updating) return;
        updaterState.checking = true;
        renderUpdateState('正在检查 GitHub 新版本...');
        try {
            var localResponse = await fetch(extensionFolderPath + '/manifest.json?t=' + Date.now(), { cache: 'no-store' });
            if (!localResponse.ok) throw new Error('本地版本读取失败，HTTP ' + localResponse.status);
            updaterState.currentVersion = parseManifestVersion(await localResponse.text());
            updaterState.latestVersion = parseManifestVersion(await fetchRemoteUpdaterFile('manifest.json'));
            updaterState.available = compareVersions(updaterState.latestVersion, updaterState.currentVersion) > 0;
            if (updaterState.available) {
                renderUpdateState('发现新版本 v' + updaterState.latestVersion + '，点击按钮即可更新并自动刷新。');
                showAutomaticUpdateNotice();
                if (isManual) showToast('success', '发现新版本 v' + updaterState.latestVersion + '，请点击立即更新');
            } else {
                renderUpdateState('当前已是最新版本 v' + updaterState.currentVersion);
                if (isManual) showToast('success', '当前已是最新版本 v' + updaterState.currentVersion);
            }
        } catch (error) {
            renderUpdateState('检查更新失败，可稍后点击重试：' + (error.message || error));
            if (isManual) showToast('error', '检查更新失败：' + (error.message || error));
            else console.warn('[' + extensionName + '] automatic update check failed', error);
        } finally {
            updaterState.checking = false;
            renderUpdateState($('#cpab-update-status').text());
        }
    }

    async function performExtensionUpdate() {
        if (updaterState.updating) return;
        updaterState.updating = true;
        renderUpdateState('正在下载并安装新版本，请不要关闭页面...');
        try {
            var context = contextGetter();
            var common = context && context.common ? context.common : context;
            var extensions = context && context.extensions ? context.extensions : {};
            var getRequestHeaders = common && common.getRequestHeaders;
            var extensionTypes = extensions && extensions.extension_types ? extensions.extension_types : (window.extension_types || {});
            if (typeof getRequestHeaders !== 'function') throw new Error('当前酒馆版本未提供扩展更新接口');
            var response = await fetch('/api/extensions/update', {
                method: 'POST',
                headers: getRequestHeaders(),
                body: JSON.stringify({
                    extensionName: extensionName,
                    global: extensionTypes[extensionName] === 'global'
                })
            });
            if (!response.ok) throw new Error((await response.text()) || ('HTTP ' + response.status));
            renderUpdateState('更新成功，即将自动刷新页面...');
            showToast('success', '默默画图更新成功，页面即将刷新');
            setTimeout(function () { window.location.reload(); }, 2200);
        } catch (error) {
            updaterState.updating = false;
            renderUpdateState('更新失败：' + (error.message || error));
            showToast('error', '更新失败：' + (error.message || error));
        }
    }

    function setStatus(text) {
        $('#cpab-status').text(String(text || ''));
    }

    function purchaseMessage() {
        return '免费额度已用完，请加QQ群联系群主获得更多额度。\n\n5元：500次\n10元：1200次\n20元：包月不限额\n\nQQ群1：118774271\nQQ群2：705941358';
    }

    function showPurchaseNotice(force) {
        if (purchaseNoticeShown && !force) return;
        purchaseNoticeShown = true;
        var message = purchaseMessage();
        if (window.toastr && window.toastr.warning) {
            window.toastr.warning(message.replace(/\n/g, '<br>'), '额度已用完', {
                closeButton: true,
                timeOut: 0,
                extendedTimeOut: 0,
                escapeHtml: false
            });
        } else {
            window.alert(message);
        }
    }

    function handleQuotaNotice(quota) {
        if (quota && quota.plan_type === 'credits' && Number(quota.remaining) <= 0) {
            showPurchaseNotice(false);
        } else if (quota && (quota.plan_type !== 'credits' || Number(quota.remaining) > 0)) {
            purchaseNoticeShown = false;
        }
    }
    function showTrialAlreadyClaimedNotice() {
        var message = '本机已经领取过免费50次额度，需要更多额度请联系群主购买。\n\n5元：500次\n10元：1200次\n20元：包月不限额\n\nQQ群1：118774271\nQQ群2：705941358';
        if (window.toastr && window.toastr.warning) {
            window.toastr.warning(message.replace(/\n/g, '<br>'), '免费额度已经领取', {
                closeButton: true,
                timeOut: 0,
                extendedTimeOut: 0,
                escapeHtml: false
            });
        } else {
            window.alert(message);
        }
    }


    function saveSettings() {
        settings.resolution = normalizeResolution(settings.resolution);
        settings.steps = normalizeSteps(settings.steps);
        Object.assign(extensionSettingsRoot[extensionName], settings);
        localStorage.setItem(storageKey, JSON.stringify(settings));
        if (typeof window.saveSettingsDebounced === 'function') window.saveSettingsDebounced();
    }

    function normalizeApiUrl(value) {
        return String(value || '').trim().replace(/\/+$/, '');
    }

    // 校验公告接口下发的地址是否合法。
    // 必须同时接受两种形式，否则插件会静默丢掉固定域名并回落到写死的旧地址：
    //   1. 固定域名（生产入口，如 https://draw.410847381.xyz）
    //   2. 快速隧道（应急回退，如 https://xxx-yyy.trycloudflare.com）
    function isAllowedApiUrl(value) {
        var url = normalizeApiUrl(value);
        if (!/^https:\/\//i.test(url)) return false;
        for (var i = 0; i < apiUrlWhitelist.length; i++) {
            var host = String(apiUrlWhitelist[i]).toLowerCase();
            // 精确匹配整个主机名，避免 evildraw.xxx 这类前缀/后缀冒充
            if (new RegExp('^https://' + host.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '$', 'i').test(url)) {
                return true;
            }
        }
        return /^https:\/\/[a-z0-9-]+\.trycloudflare\.com$/i.test(url);
    }


    async function refreshDiscoveredApiUrl(force, silent) {
        var now = Date.now();
        if (!force && normalizeApiUrl(settings.apiUrl) && now - lastEndpointDiscoveryAt < endpointDiscoveryIntervalMs) {
            return normalizeApiUrl(settings.apiUrl);
        }
        if (endpointDiscoveryPromise) return endpointDiscoveryPromise;
        endpointDiscoveryPromise = (async function () {
            var response;
            try {
                response = await fetch(endpointDiscoveryUrl + '?t=' + Date.now(), { method: 'GET', cache: 'no-store' });
            } catch (error) {
                if (!silent) showToast('error', '无法查询最新服务器地址：' + (error.message || error));
                throw new Error('无法查询最新服务器地址');
            }
            var data;
            try { data = await response.json(); }
            catch (error) { throw new Error('服务器地址公告返回格式错误'); }
            if (!response.ok || !data || data.ok === false || !data.api_url) {
                throw new Error((data && data.error) || '服务器地址公告暂不可用');
            }
            var discovered = normalizeApiUrl(data.api_url);
            if (!isAllowedApiUrl(discovered)) {
                console.warn('[' + extensionName + '] 公告接口下发了不在白名单内的地址，已忽略：', discovered);
                throw new Error('服务器地址公告中的网址无效：' + discovered
                    + '（插件白名单：' + apiUrlWhitelist.join(', ') + '）');
            }
            var changed = discovered !== normalizeApiUrl(settings.apiUrl);
            settings.apiUrl = discovered;
            lastEndpointDiscoveryAt = Date.now();
            saveSettings();
            $('#cpab-api-url').val(discovered);
            if (changed && !silent) showToast('success', '已自动获取最新画图服务器地址');
            return discovered;
        })();
        try { return await endpointDiscoveryPromise; }
        finally { endpointDiscoveryPromise = null; }
    }

    function requireApiUrl() {
        var apiUrl = normalizeApiUrl(settings.apiUrl);
        if (!apiUrl) throw new Error('请先填写网址');
        if (!/^https?:\/\//i.test(apiUrl)) throw new Error('网址必须以 http:// 或 https:// 开头');
        return apiUrl;
    }

    function createInstallId() {
        if (window.crypto && typeof window.crypto.randomUUID === 'function') {
            return window.crypto.randomUUID().replace(/-/g, '');
        }
        if (window.crypto && typeof window.crypto.getRandomValues === 'function') {
            var bytes = new Uint8Array(24);
            window.crypto.getRandomValues(bytes);
            return Array.from(bytes).map(function (value) { return value.toString(16).padStart(2, '0'); }).join('');
        }
        return 'install_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);
    }

    function ensureInstallId() {
        var installId = String(settings.installId || '').trim();
        if (!/^[A-Za-z0-9_-]{16,128}$/.test(installId)) {
            installId = createInstallId();
            settings.installId = installId;
            saveSettings();
        }
        return installId;
    }

    async function claimTrialKey(apiUrl, silent) {
        if (trialClaimPromise) return trialClaimPromise;
        trialClaimPromise = (async function () {
            setStatus('正在领取新用户50次免费额度...');
            var response;
            try {
                response = await fetch(apiUrl + '/v1/trial', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ install_id: ensureInstallId() })
                });
            } catch (error) {
                throw new Error('无法领取免费额度：' + (error.message || error));
            }
            var data;
            try { data = await response.json(); }
            catch (error) { throw new Error('免费额度接口返回的不是 JSON，HTTP ' + response.status); }
            if (!response.ok || !data || data.ok === false || !data.api_key) {
                var claimError = new Error((data && data.error) || ('免费额度领取失败，HTTP ' + response.status));
                claimError.status = response.status;
                claimError.payload = data;
                throw claimError;
            }
            if (!data.created) {
                setStatus('本机已经领取过免费50次额度');
                if (!silent) showTrialAlreadyClaimedNotice();
                return data;
            }
            settings.apiKey = String(data.api_key);
            saveSettings();
            $('#cpab-api-key').val(settings.apiKey);
            setStatus('已领取新用户50次免费额度，可以直接画图');
            if (!silent) showToast('success', '免费50次额度领取成功，卡密已自动填写');
            return data;
        })();
        try { return await trialClaimPromise; }
        finally { trialClaimPromise = null; }
    }

    async function requireConnectionSettings() {
        await refreshDiscoveredApiUrl(false, true);
        var apiUrl = requireApiUrl();
        var apiKey = String(settings.apiKey || '').trim();
        if (!apiKey) throw new Error('请先点击“领取免费50次”；免费额度用完后，请加QQ群联系群主购买卡密');
        return { apiUrl: apiUrl, apiKey: apiKey };
    }

    async function apiRequest(path, options) {
        var connection = await requireConnectionSettings();
        var requestOptions = Object.assign({}, options || {});
        requestOptions.headers = Object.assign({
            'X-API-Key': connection.apiKey,
            'Content-Type': 'application/json'
        }, requestOptions.headers || {});
        var response;
        try {
            response = await fetch(connection.apiUrl + path, requestOptions);
        } catch (error) {
            var previousUrl = connection.apiUrl;
            try {
                var latestUrl = await refreshDiscoveredApiUrl(true, true);
                if (latestUrl && latestUrl !== previousUrl) {
                    connection.apiUrl = latestUrl;
                    response = await fetch(connection.apiUrl + path, requestOptions);
                }
            } catch (discoveryError) {
                console.warn('[' + extensionName + '] endpoint rediscovery failed', discoveryError);
            }
            if (!response) throw new Error('无法连接服务器：' + (error.message || error));
        }
        var data;
        try {
            data = await response.json();
        } catch (error) {
            throw new Error('API 返回的不是 JSON，HTTP ' + response.status);
        }
        if (!response.ok || !data || data.ok === false) {
            var apiError = new Error((data && data.error) || ('API 请求失败，HTTP ' + response.status));
            apiError.status = response.status;
            apiError.payload = data;
            throw apiError;
        }
        return data;
    }

    function formatDate(value) {
        if (!value) return '—';
        var date = new Date(value);
        return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleString('zh-CN', { hour12: false });
    }

    function formatQuota(quota) {
        if (!quota) return '额度数据为空';
        var name = quota.name ? '【' + quota.name + '】 ' : '';
        if (quota.plan_type === 'credits') {
            return name + '次数卡：剩余 ' + quota.remaining + ' / ' + quota.total + ' 次，已使用 ' + quota.used + ' 次';
        }
        if (!quota.activated) {
            return name + '时长卡：未激活；首次成功出图后开始计算 ' + quota.duration_days + ' 天';
        }
        return name + '时长卡：剩余约 ' + quota.days_remaining + ' 天；到期时间 ' + formatDate(quota.expires_at);
    }

    async function refreshQuota(silent) {
        var $quota = $('#cpab-quota');
        $quota.removeClass('is-ok is-error').addClass('is-idle').text('正在查询额度...');
        try {
            var data = await apiRequest('/v1/quota', { method: 'GET' });
            lastKnownQuota = data.quota;
            $quota.removeClass('is-idle is-error').addClass('is-ok').text(formatQuota(data.quota));
            handleQuotaNotice(data.quota);
            renderResolutionNote();
            return data.quota;
        } catch (error) {
            $quota.removeClass('is-idle is-ok').addClass('is-error').text(error.message || String(error));
            if (!silent) showToast('error', error.message || String(error));
            throw error;
        }
    }

    function queueText() {
        return queueState === 'offline' ? '队列离线' : '前方 ' + lastQueueAhead;
    }

    /* 高清档在楼层徽标上直接标出消耗，用户不用翻设置也知道这次要花 2 次 */
    function queueTextWithCost() {
        var base = queueText();
        var cost = creditCostOf(settings.resolution);
        if (cost > 1) {
            return base + ' · 高清扣 ' + cost + ' 次';
        }
        return base;
    }

    function updateQueueBadges() {
        var stateClass = queueState === 'offline' ? 'is-offline' : (lastQueueAhead > 0 ? 'is-busy' : 'is-idle');
        var text = queueTextWithCost();
        $('.cpab-queue-badge').removeClass('is-idle is-busy is-offline').addClass(stateClass).text(text);
        $('#cpab-queue-status').removeClass('is-idle is-busy is-offline').addClass(stateClass).text('服务器队列：' + text);
    }

    async function refreshQueueStatus(silent) {
        if (queuePollBusy) return;
        if (!normalizeApiUrl(settings.apiUrl) || !String(settings.apiKey || '').trim()) {
            queueState = 'offline';
            updateQueueBadges();
            return;
        }
        queuePollBusy = true;
        try {
            var data = await apiRequest('/v1/status', { method: 'GET' });
            lastQueueAhead = Math.max(0, Number(data.queue && data.queue.ahead) || 0);
            queueState = 'online';
            updateQueueBadges();
        } catch (error) {
            queueState = 'offline';
            updateQueueBadges();
            if (!silent) showToast('error', error.message || String(error));
        } finally {
            queuePollBusy = false;
        }
    }

    function cleanPrompt(value) {
        var prompt = String(value || '');
        prompt = prompt.replace(/<br\s*\/?\s*>/gi, '\n');
        prompt = prompt.replace(/<\/?p(?:\s[^>]*)?>/gi, '\n');
        prompt = prompt.replace(/<\/?(?:details|summary)(?:\s[^>]*)?>/gi, '');
        prompt = $('<textarea>').html(prompt).text();
        prompt = prompt.replace(/^\s*(?:\x60{3}[a-z0-9_-]*\s*)?/i, '');
        prompt = prompt.replace(/\s*\x60{3}\s*$/i, '');
        return prompt.trim();
    }

    function extractImagePrompt(messageText) {
        var text = String(messageText || '').trim();
        if (!text) throw new Error('消息内容为空，无法提取提示词');
        var patterns = [
            /\[ImagePrompt\|([\s\S]*?)\](?![\s\S]*\[ImagePrompt\|)/i,
            /<ImagePrompt(?:\s[^>]*)?>([\s\S]*?)<\/ImagePrompt>/i,
            /<image_prompt(?:\s[^>]*)?>([\s\S]*?)<\/image_prompt>/i,
            /<details(?:\s[^>]*)?>[\s\S]*?<summary(?:\s[^>]*)?>\s*(?:绘画|绘图|出图|图片|Image)\s*提示词\s*<\/summary>([\s\S]*?)<\/details>/i,
            /【\s*(?:绘画|绘图|出图|图片)\s*提示词\s*】\s*([\s\S]*?)(?=\n\s*【|$)/i,
            /(?:^|\n)\s*(?:#{1,6}\s*)?(?:绘画|绘图|出图|图片)\s*提示词\s*[：:]\s*([\s\S]*?)(?=\n\s*(?:#{1,6}\s*)?(?:负面提示词|Negative\s*Prompt|正文|说明)\s*[：:]|$)/i
        ];
        for (var i = 0; i < patterns.length; i++) {
            var match = text.match(patterns[i]);
            var prompt = match && cleanPrompt(match[1]);
            if (prompt) return prompt;
        }
        throw new Error('没有识别到绘画提示词');
    }

    function messageHasPrompt(message) {
        if (!message || message.is_user || !message.mes) return false;
        try {
            return !!extractImagePrompt(message.mes);
        } catch (error) {
            return false;
        }
    }

    function getButtonContainer($mes) {
        var $container = $mes.find('.cpab-bottom-buttons').first();
        if ($container.length) return $container;
        var $text = $mes.find('.mes_text').first();
        if ($text.length) {
            $container = $('<div class="cpab-bottom-buttons"></div>');
            $text.after($container);
            return $container;
        }
        var $block = $mes.find('.mes_block').first();
        if ($block.length) {
            $container = $('<div class="cpab-bottom-buttons"></div>');
            $block.append($container);
            return $container;
        }
        return $mes.find('.extraMesButtons').first().length ? $mes.find('.extraMesButtons').first() : $mes.find('.mes_buttons').first();
    }

    function ensureButtonForMessage(messageId) {
        var context = contextGetter();
        var message = context && context.chat ? context.chat[messageId] : null;
        var $mes = $('.mes[mesid="' + messageId + '"]');
        if (!$mes.length) return;
        if (!messageHasPrompt(message)) {
            $mes.find('.cpab-bottom-buttons').remove();
            return;
        }
        var $target = getButtonContainer($mes);
        if (!$target.length) return;
        if (!$target.find('.cpab-mes-button').length) {
            $target.append('<div class="mes_button cpab-mes-button" role="button" tabindex="0" title="生成图片"><i class="fa-solid fa-image"></i></div>');
        }
        if (!$target.find('.cpab-random-button').length) {
            $target.append('<div class="mes_button cpab-random-button" role="button" tabindex="0" title="随机重绘"><i class="fa-solid fa-rotate"></i></div>');
        }
        if (!$target.find('.cpab-optimize-button').length) {
            $target.append('<div class="mes_button cpab-optimize-button" role="button" tabindex="0" title="固定种子，步数 +2 优化（最高 8 步）"><i class="fa-solid fa-wand-magic-sparkles"></i></div>');
        }
        if (!$target.find('.cpab-queue-badge').length) {
            $target.append('<span class="cpab-queue-badge" title="当前提交任务前预计需要等待的任务数"></span>');
        }
        if (!$target.find('.cpab-inline-style-row').length) {
            var $styleRow = $('<label class="cpab-inline-style-row"><span>画风</span><select class="cpab-inline-style-select text_pole" title="切换本层及后续生图使用的画风"></select></label>');
            $target.append($styleRow);
            populateStylePresetSelect($styleRow.find('.cpab-inline-style-select'));
        }
        $target.find('.cpab-mes-button, .cpab-random-button, .cpab-optimize-button').attr('data-cpab-mesid', String(messageId));
        $target.find('.cpab-inline-style-select').val(getStylePreset(settings.stylePreset).id);
        updateQueueBadges();
    }

    function refreshButtons() {
        var context = contextGetter();
        var chat = context && context.chat ? context.chat : [];
        chat.forEach(function (_, index) { ensureButtonForMessage(index); });
    }

    function setButtonState($button, state, title) {
        if (!$button || !$button.length) return;
        $button.removeClass('is-loading is-success is-error');
        if (state) $button.addClass(state);
        if (title) $button.attr('title', title);
    }

    function getGenerationMeta(messageId) {
        var context = contextGetter();
        var message = context && context.chat ? context.chat[messageId] : null;
        var meta = message && message.extra ? message.extra.cpab_last_generation : null;
        return meta && typeof meta === 'object' ? meta : null;
    }

    /* ==================== 图片压缩（保存到酒馆前） ====================
       服务端返回的是 PNG，720p 常有 1.5~2.5MB，直接存进酒馆会让聊天记录变臃肿、
       手机上滚楼层也卡。这里转成 JPEG 再上传，画质设得比网页版预览更高（0.90），
       因为酒馆里点开看大图是常见操作。
       压缩在浏览器本地完成，不占服务器资源；任何失败都退回原始数据，
       绝不能让「压缩」把出图流程搞挂。 */
    var STORE_JPEG_QUALITY = 0.90;

    function compressForStorage(base64Data, format) {
        return new Promise(function (resolve) {
            var raw = String(base64Data || '');
            var fmt = String(format || 'png').toLowerCase();
            /* 服务端本来就给 JPEG 的就不用再转一次（二次压缩只会掉画质） */
            if (!raw || fmt === 'jpg' || fmt === 'jpeg') {
                resolve({ data: raw, format: fmt === 'jpeg' ? 'jpg' : (fmt || 'png') });
                return;
            }
            var settled = false;
            var finish = function (value) {
                if (settled) { return; }
                settled = true;
                resolve(value);
            };
            /* 兜底：3 秒没转完就按原图走，宁可大一点也不能卡住 */
            var timer = setTimeout(function () {
                finish({ data: raw, format: fmt || 'png' });
            }, 3000);
            try {
                var image = new Image();
                image.onload = function () {
                    try {
                        var w = image.naturalWidth || image.width;
                        var h = image.naturalHeight || image.height;
                        if (!w || !h) { clearTimeout(timer); finish({ data: raw, format: fmt || 'png' }); return; }
                        var canvas = document.createElement('canvas');
                        canvas.width = w;
                        canvas.height = h;
                        var ctx = canvas.getContext('2d');
                        if (!ctx) { clearTimeout(timer); finish({ data: raw, format: fmt || 'png' }); return; }
                        /* 铺白底，避免透明区域在 JPEG 里变黑 */
                        ctx.fillStyle = '#ffffff';
                        ctx.fillRect(0, 0, w, h);
                        ctx.drawImage(image, 0, 0, w, h);
                        var url = canvas.toDataURL('image/jpeg', STORE_JPEG_QUALITY);
                        var marker = 'base64,';
                        var at = url.indexOf(marker);
                        var b64 = at >= 0 ? url.slice(at + marker.length) : '';
                        clearTimeout(timer);
                        if (b64 && b64.length > 64 && b64.length < raw.length) {
                            var saved = Math.round((1 - b64.length / raw.length) * 100);
                            console.log('[默默画图] 图片已压缩 ' + raw.length + ' -> ' + b64.length +
                                ' 字符（省 ' + saved + '%）');
                            finish({ data: b64, format: 'jpg' });
                        } else {
                            finish({ data: raw, format: fmt || 'png' });
                        }
                    } catch (error) {
                        clearTimeout(timer);
                        finish({ data: raw, format: fmt || 'png' });
                    }
                };
                image.onerror = function () { clearTimeout(timer); finish({ data: raw, format: fmt || 'png' }); };
                image.src = 'data:image/png;base64,' + raw;
            } catch (error) {
                clearTimeout(timer);
                finish({ data: raw, format: fmt || 'png' });
            }
        });
    }

    async function uploadImage(base64Data, format) {
        var context = contextGetter();
        var characterName = String((context && (context.name2 || context.characterName)) || 'ComfyUI-Public').trim();
        var payload = {
            image: base64Data,
            format: format || 'png',
            ch_name: characterName || 'ComfyUI-Public',
            filename: 'public_api_' + Date.now()
        };
        var data;
        try {
            data = await $.ajax({
                url: '/api/images/upload',
                method: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(payload)
            });
        } catch (error) {
            var details = error && (error.responseJSON || error.responseText || error.statusText);
            throw new Error('图片保存到酒馆失败：' + (typeof details === 'string' ? details : JSON.stringify(details || error)));
        }
        if (!data || !data.path) throw new Error('酒馆没有返回图片保存路径');
        return data.path;
    }

    async function emitMessageUpdated(messageId) {
        var eventSource = window.eventSource || (window.SillyTavern && window.SillyTavern.eventSource);
        var eventTypes = window.event_types || (window.SillyTavern && window.SillyTavern.event_types) || {};
        if (eventSource && eventSource.emit && eventTypes.MESSAGE_UPDATED) {
            await eventSource.emit(eventTypes.MESSAGE_UPDATED, Number(messageId));
        }
    }

    async function saveChatSafe() {
        var context = contextGetter();
        if (context && typeof context.saveChat === 'function') {
            await context.saveChat();
        }
    }

    function delay(ms) {
        return new Promise(function (resolve) { setTimeout(resolve, ms); });
    }

    async function forceSaveViaOfficialEditor(messageId, messageText) {
        var scrollContainer = document.querySelector('#chat');
        var previousScrollTop = scrollContainer ? scrollContainer.scrollTop : null;
        var $messageBlock = $('#chat .mes[mesid="' + messageId + '"]');
        if (!$messageBlock.length) return false;

        var $editButton = $messageBlock.find('.mes_edit').first();
        if (!$editButton.length) return false;
        $editButton.trigger('click');
        await delay(60);

        var $textarea = $messageBlock.find('.edit_textarea:visible').first();
        if (!$textarea.length) return false;
        $textarea.val(String(messageText || ''));
        var textareaElement = $textarea.get(0);
        if (textareaElement) {
            textareaElement.dispatchEvent(new Event('input', { bubbles: true }));
            textareaElement.dispatchEvent(new Event('change', { bubbles: true }));
        }

        await delay(60);
        var $doneButton = $messageBlock.find('.mes_edit_done:visible').first();
        if (!$doneButton.length) return false;
        $doneButton.trigger('click');
        await delay(150);

        if (scrollContainer && previousScrollTop !== null) {
            scrollContainer.scrollTop = previousScrollTop;
        }
        return true;
    }

    async function injectImage(messageId, imageUrl, prompt, quota, generationMeta) {
        var context = contextGetter();
        var message = context && context.chat ? context.chat[messageId] : null;
        if (!message) throw new Error('找不到目标楼层');
        message.extra = message.extra || {};
        message.extra.media = Array.isArray(message.extra.media) ? message.extra.media : [];
        message.extra.media.push({ url: imageUrl, title: prompt, type: 'image', source: 'generated' });
        message.extra.media_index = message.extra.media.length - 1;
        message.extra.inline_image = true;
        message.extra.image = imageUrl;
        message.extra.cpab_last_prompt = prompt;
        message.extra.cpab_last_quota = quota || null;
        message.extra.cpab_last_generation = generationMeta;
        var scenePrompt = generationMeta && generationMeta.scenePrompt ? generationMeta.scenePrompt : prompt;
        message.extra.cpab_auto_generated_prompt = scenePrompt;
        markMessageGenerated(messageId, scenePrompt);

        if (
            Array.isArray(message.swipes)
            && typeof message.swipe_id === 'number'
            && message.swipes[message.swipe_id] !== undefined
        ) {
            message.swipes[message.swipe_id] = message.mes;
        }

        await saveChatSafe();
        await emitMessageUpdated(messageId);
        var editorRefreshed = await forceSaveViaOfficialEditor(messageId, message.mes);
        if (!editorRefreshed) {
            await emitMessageUpdated(messageId);
        }
        refreshButtons();
    }

    function isHighResolution(value) {
        return highResolutions.indexOf(normalizeResolution(value)) >= 0;
    }

    /* 本次生成要花几次额度：高清档 2 次，普通档 1 次。
       与网关的像素判定规则保持一致（超过 512x768 像素总数即高清）。 */
    function creditCostOf(value) {
        return isHighResolution(value) ? HIGH_RES_CREDIT_COST : 1;
    }

    function readGenerationOptions() {
        var resolution = normalizeResolution(settings.resolution);
        var parts = resolution.split('x');
        return {
            width: Number(parts[0]),
            height: Number(parts[1]),
            steps: normalizeSteps(settings.steps),
            resolution: resolution,
            cost: creditCostOf(resolution),
            highRes: isHighResolution(resolution)
        };
    }

    /* 在分辨率下拉下方提示当前档位要花几次，并在按钮标题上同步 */
    function renderResolutionNote() {
        var options = readGenerationOptions();
        var $note = $('#cpab-res-note');
        if ($note.length) {
            if (options.highRes) {
                var remaining = lastKnownQuota && lastKnownQuota.plan_type === 'credits'
                    ? Number(lastKnownQuota.remaining)
                    : null;
                var extra = '';
                if (remaining !== null && Number.isFinite(remaining)) {
                    extra = remaining < options.cost
                        ? '⚠️ 当前仅剩 ' + remaining + ' 次，不足以生成这张高清图。'
                        : '当前剩余 ' + remaining + ' 次，本次将扣 ' + options.cost + ' 次，生成后剩 ' + (remaining - options.cost) + ' 次。';
                }
                $note.removeClass('is-plain').addClass('is-warn').text(
                    '高清档 ' + options.resolution + '：生成慢约 10 秒，每次消耗 ' + options.cost + ' 次额度。' + extra
                );
            } else {
                $note.removeClass('is-warn').addClass('is-plain').text(
                    '普通档 ' + options.resolution + '：每次消耗 ' + options.cost + ' 次额度。'
                );
            }
        }
    }

    function buildGenerationRequest(messageId, mode) {
        var options = readGenerationOptions();
        var last = getGenerationMeta(messageId);
        var payload = { width: options.width, height: options.height, steps: options.steps };
        var actionLabel = '生成图片';
        if (mode === 'random') {
            payload.steps = last && allowedSteps.indexOf(Number(last.steps)) >= 0 ? Number(last.steps) : options.steps;
            actionLabel = '随机重绘';
        }
        if (mode === 'optimize') {
            if (!last) throw new Error('这层还没有历史图片，请先点一次生成图片或随机重绘');
            if (!Number.isFinite(Number(last.seed))) throw new Error('找不到上一次生成的 seed');
            if (!Number.isFinite(Number(last.steps))) throw new Error('找不到上一次生成的步数');
            payload.seed = Number(last.seed);
            payload.steps = Math.min(8, Number(last.steps) + 2);
            actionLabel = '固定 seed 优化（' + last.steps + ' → ' + payload.steps + ' 步）';
        }
        // 把本次要消耗的次数写进按钮提示，高清档会显示「扣 2 次」
        if (options.cost > 1) {
            actionLabel += '｜高清扣 ' + options.cost + ' 次';
        }
        return { payload: payload, actionLabel: actionLabel };
    }

    async function generateForMessage(messageId, $button, mode) {
        var context = contextGetter();
        var message = context && context.chat ? context.chat[messageId] : null;
        if (!message) throw new Error('找不到对应楼层消息');
        var scenePrompt = extractImagePrompt(message.mes);
        var selectedStyle = getStylePreset(settings.stylePreset);
        var selectedStyleUi = getStylePresetUi(selectedStyle.id);
        var prompt = buildStyledPrompt(scenePrompt, selectedStyle.id);
        // 本次实际使用的分辨率与应扣次数（高清档为 2）
        var genOptions = readGenerationOptions();
        var request = buildGenerationRequest(messageId, mode || 'normal');
        request.payload.prompt = prompt;
        setButtonState($button, 'is-loading', request.actionLabel + '中');
        await refreshQueueStatus(true);
        setStatus('楼层 ' + messageId + '：' + request.actionLabel + '，服务器前方 ' + lastQueueAhead + ' 个任务');
        try {
            var data = await apiRequest('/v1/generate', { method: 'POST', body: JSON.stringify(request.payload) });
            setStatus('出图完成，正在保存到酒馆...');
            /* 先压缩再上传：PNG 原图常有 1.5~2.5MB，跨洋隧道传输很慢，
               转成 JPEG 后体积约为原来的 1/5，聊天记录也更清爽。 */
            var packed = await compressForStorage(data.data, data.format || 'png');
            var imageUrl = await uploadImage(packed.data, packed.format);
            var generationMeta = {
                seed: Number(data.seed),
                steps: Number(data.steps),
                prompt: prompt,
                scenePrompt: scenePrompt,
                stylePreset: selectedStyle.id,
                styleName: selectedStyleUi.label,
                styleEnglishName: selectedStyle.name,
                imageUrl: imageUrl,
                savedAt: Date.now()
            };
            await injectImage(messageId, imageUrl, prompt, data.quota, generationMeta);
            if (data.quota) { lastKnownQuota = data.quota; }
            $('#cpab-quota').removeClass('is-idle is-error').addClass('is-ok').text(formatQuota(data.quota));
            handleQuotaNotice(data.quota);
            renderResolutionNote();
            var charged = Number(data.credits_charged) || genOptions.cost || 1;
            var chargedText = charged > 1 ? '，本次消耗 ' + charged + ' 次' : '';
            setButtonState($button, 'is-success', '出图成功，点击可再次生成');
            setStatus('楼层 ' + messageId + '：出图完成，seed=' + data.seed + '，steps=' + data.steps + chargedText);
            showToast('success', '图片已注入楼层，' + formatQuota(data.quota));
            setTimeout(function () {
                setButtonState($button, '', mode === 'random' ? '随机重绘' : (mode === 'optimize' ? '固定种子，步数 +2 优化（最高 8 步）' : '生成图片'));
            }, 2500);
        } finally {
            refreshQueueStatus(true).catch(function () {});
        }
    }

    async function handleGenerateClick(event, mode) {
        event.preventDefault();
        event.stopPropagation();
        var $button = $(event.currentTarget);
        var messageId = Number($button.attr('data-cpab-mesid'));
        try {
            await generateForMessage(messageId, $button, mode);
        } catch (error) {
            setButtonState($button, 'is-error', '生图失败，点击重试');
            setStatus('生图失败：' + (error.message || error));
            showToast('error', error.message || String(error));
            if (Number(error.status) === 402 || /次数已用完|卡密已过期/.test(String(error.message || ''))) showPurchaseNotice(true);
            refreshQuota(true).catch(function () {});
            refreshQueueStatus(true).catch(function () {});
        }
    }

    function loadSettingsToUi() {
        $('#cpab-api-url').val(settings.apiUrl || '');
        $('#cpab-api-key').val(settings.apiKey || '');
        $('#cpab-resolution').val(normalizeResolution(settings.resolution));
        $('#cpab-steps').val(String(normalizeSteps(settings.steps)));
        $('#cpab-auto-generate').prop('checked', Boolean(settings.autoGenerate));
        renderStylePresetSelect();
        renderResolutionNote();
        updateQueueBadges();
        /* 去服务端把自定义画风取回来，追加进下拉框（没卡密时静默跳过） */
        refreshCustomStyles();
    }

    function populateStylePresetSelect($select) {
        var selected = getStylePreset(settings.stylePreset);
        if (!$select.length) return;
        $select.each(function () {
            var $current = $(this);
            $current.empty();
            var groups = {};
            stylePresets.forEach(function (preset) {
                var ui = getStylePresetUi(preset.id);
                if (!groups[ui.group]) {
                    groups[ui.group] = $('<optgroup></optgroup>').attr('label', ui.group);
                    $current.append(groups[ui.group]);
                }
                groups[ui.group].append($('<option></option>').val(preset.id).text(ui.label));
            });
            /* 下拉框里只放真正的画风。
               自定义画风在下面的「自定义画风」区里新建/管理，不用在下拉框里再放一个入口。 */
            $current.val(selected.id);
        });
    }

    function syncStylePresetControls() {
        /* 自定义画风还没从服务器拉回来时先不做规范化。
           因为 getStylePreset() 找不到 id 会回退到默认画风，
           如果用户上次选的是自定义画风，这里提前规范化会把它悄悄改掉。
           等 refreshCustomStyles() 拿到数据后再统一处理。 */
        if (customStylesPending) { return; }
        settings.stylePreset = normalizeStylePreset(settings.stylePreset);
        var selected = getStylePreset(settings.stylePreset);
        var selectedUi = getStylePresetUi(selected.id);
        $('#cpab-style-select, .cpab-inline-style-select').val(selected.id);
        $('#cpab-style-current').text('当前风格：' + selectedUi.label);
        $('#cpab-style-description').text(selectedUi.description);
    }

    function renderStylePresetSelect() {
        populateStylePresetSelect($('#cpab-style-select'));
        syncStylePresetControls();
    }

    /* ==================== 自定义风格 ====================
       存在服务端并绑定卡密，所以和网页版共用同一份——用户在网页版存的风格
       这里直接能选，不用重复添加。
       实现方式是在运行时把自定义风格追进 stylePresets / stylePresetUi，
       这样 getStylePreset / buildStyledPrompt 等原有逻辑一行都不用改。 */
    var CUSTOM_STYLE_ID_PREFIX = 'custom-';
    var customStylePresets = [];
    var baseStylePresets = stylePresets.slice();
    var baseStylePresetUi = Object.assign({}, stylePresetUi);
    /* 自定义画风是否还没加载完。未加载完之前不要规范化 stylePreset，否则会丢选择 */
    var customStylesPending = false;

    function isCustomStyleId(id) {
        return String(id || '').indexOf(CUSTOM_STYLE_ID_PREFIX) === 0;
    }

    function findCustomStyle(id) {
        var want = String(id || '');
        for (var i = 0; i < customStylePresets.length; i++) {
            if (customStylePresets[i].id === want) { return customStylePresets[i]; }
        }
        return null;
    }

    /* 把「内置 + 自定义」重新拼成一份，内置排前面、自定义单独一组放后面 */
    function rebuildStylePresets() {
        stylePresets = baseStylePresets.concat(customStylePresets);
        stylePresetUi = Object.assign({}, baseStylePresetUi);
        customStylePresets.forEach(function (preset) {
            stylePresetUi[preset.id] = {
                label: preset.name,
                group: '⭐ 我的自定义风格',
                description: preset.description || '你自己保存的画风，点击即用。'
            };
        });
    }

    function customStyleApi(path, options) {
        return apiRequest(path, options);   /* 复用插件的请求层：自动带卡密、自动重试换地址 */
    }

    function refreshCustomStyles() {
        if (!settings.apiKey) {
            /* 没卡密也要收尾，否则规范化会一直被跳过 */
            customStylesPending = false;
            renderStylePresetSelect();
            renderCustomStyleList();
            return Promise.resolve([]);
        }
        customStylesPending = true;
        return customStyleApi('/v1/styles').then(function (data) {
            customStylePresets = (data.styles || []).map(function (s) {
                return {
                    id: CUSTOM_STYLE_ID_PREFIX + s.id,
                    serverId: s.id,
                    name: String(s.name || ''),
                    label: String(s.name || ''),
                    description: '自定义画风（网页版与插件共用）',
                    promptTitle: String(s.name || ''),
                    prefix: String(s.prefix || ''),
                    suffix: String(s.suffix || '')
                };
            }).filter(function (p) { return p.name; });
            customStylesPending = false;
            rebuildStylePresets();
            renderStylePresetSelect();
            renderCustomStyleList();
            return customStylePresets;
        }).catch(function (error) {
            /* 没卡密 / 网络不通都不能影响正常生图，静默跳过 */
            console.warn('[默默画图] 自定义画风读取失败：', error && error.message);
            customStylesPending = false;
            renderStylePresetSelect();
            renderCustomStyleList();
            return customStylePresets;
        });
    }

    function renderCustomStyleList() {
        var $list = $('#cpab-custom-list');
        if (!$list.length) { return; }
        if (!customStylePresets.length) {
            $list.html('<div class="cpab-custom-empty">还没有自定义画风。填好下面的内容点「保存画风」，' +
                '保存后这里和网页版都能直接选用。</div>');
            return;
        }
        $list.empty();
        customStylePresets.forEach(function (preset) {
            var $item = $('<div class="cpab-custom-item"></div>');
            $item.append($('<div class="cpab-custom-item-main"></div>')
                .append($('<div class="cpab-custom-item-name"></div>').text(preset.name))
                .append($('<div class="cpab-custom-item-desc"></div>')
                    .text(String(preset.prefix || preset.suffix || '').slice(0, 60))));
            var $actions = $('<div class="cpab-custom-item-actions"></div>');
            $('<button class="menu_button" type="button">编辑</button>')
                .on('click', function () { fillCustomStyleForm(preset.id); })
                .appendTo($actions);
            $('<button class="menu_button" type="button">删除</button>')
                .on('click', function () { deleteCustomStyle(preset.id); })
                .appendTo($actions);
            $item.append($actions);
            $list.append($item);
        });
    }

    function setCustomStyleError(message) {
        var $el = $('#cpab-custom-error');
        if (!$el.length) { return; }
        if (!message) { $el.addClass('hidden').text(''); return; }
        $el.removeClass('hidden').text(String(message));
    }

    function setCustomStyleTip(message) {
        var $el = $('#cpab-custom-tip');
        if (!$el.length) { return; }
        if (!message) { $el.addClass('hidden').text(''); return; }
        $el.removeClass('hidden').text(String(message));
    }

    var editingCustomStyleId = null;

    function syncCustomStyleMode() {
        var editing = editingCustomStyleId ? findCustomStyle(editingCustomStyleId) : null;
        var $btn = $('#cpab-custom-save');
        if ($btn.length) {
            $btn.text(editing ? '更新这个画风' : '保存为新画风');
        }
        if (editing) {
            var name = String($('#cpab-custom-name').val() || '').trim() || editing.name;
            setCustomStyleTip('正在编辑「' + editing.name + '」：保存会把它的内容改为上面填的样子' +
                (name !== editing.name ? '，名称会改成「' + name + '」' : '') + '。');
        }
    }

    function clearCustomStyleForm() {
        editingCustomStyleId = null;
        $('#cpab-custom-name').val('');
        $('#cpab-custom-prefix').val('');
        $('#cpab-custom-suffix').val('');
        setCustomStyleError('');
        setCustomStyleTip('');
        renderCustomStyleList();
        syncCustomStyleMode();
    }

    function fillCustomStyleForm(styleId) {
        var preset = findCustomStyle(styleId);
        if (!preset) { return; }
        editingCustomStyleId = styleId;
        $('#cpab-custom-name').val(preset.name);
        $('#cpab-custom-prefix').val(preset.prefix);
        $('#cpab-custom-suffix').val(preset.suffix);
        setCustomStyleError('');
        renderCustomStyleList();
        syncCustomStyleMode();
        $('#cpab-custom-name').trigger('focus');
    }

    function saveCustomStyle() {
        var name = String($('#cpab-custom-name').val() || '').trim();
        var prefix = String($('#cpab-custom-prefix').val() || '').trim();
        var suffix = String($('#cpab-custom-suffix').val() || '').trim();
        if (!name) { setCustomStyleError('请填写画风名称'); return; }
        if (name === '无风格') { setCustomStyleError('这个名称是内置的，请换一个'); return; }
        if (!prefix && !suffix) { setCustomStyleError('画风描述和补充说明至少要填一个'); return; }
        if (!settings.apiKey) { setCustomStyleError('请先在上方填写卡密，自定义画风跟卡密绑定'); return; }

        var payload = { name: name, prefix: prefix, suffix: suffix };
        if (editingCustomStyleId) {
            var current = findCustomStyle(editingCustomStyleId);
            if (current && current.serverId) { payload.id = current.serverId; }
        }
        var wasEditing = !!editingCustomStyleId;
        var $btn = $('#cpab-custom-save');
        $btn.prop('disabled', true).text('保存中…');
        setCustomStyleError('');

        customStyleApi('/v1/styles', { method: 'POST', body: JSON.stringify(payload) })
            .then(function (data) {
                var savedName = String((data.style && data.style.name) || name);
                var savedId = data.style && data.style.id;
                editingCustomStyleId = null;
                return refreshCustomStyles().then(function () {
                    /* 保存完直接切过去，用户马上能用 */
                    if (savedId) {
                        applyStylePresetSelection(CUSTOM_STYLE_ID_PREFIX + savedId);
                    } else if (savedName) {
                        var match = customStylePresets.filter(function (p) { return p.name === savedName; })[0];
                        if (match) { applyStylePresetSelection(match.id); }
                    }
                    clearCustomStyleForm();
                    setCustomStyleTip(wasEditing ? '画风已更新，网页版和插件都能用' : '画风已保存，网页版和插件都能用');
                    showToast('success', wasEditing ? '画风已更新' : '画风已保存');
                });
            })
            .catch(function (error) {
                setCustomStyleError((error && error.message) || '保存失败，请重试');
            })
            .then(function () {
                $btn.prop('disabled', false);
                syncCustomStyleMode();
            });
    }

    function deleteCustomStyle(styleId) {
        var preset = findCustomStyle(styleId);
        if (!preset) { return; }
        if (!window.confirm('确定删除画风「' + preset.name + '」？删除后网页版和插件里都会没有。')) { return; }
        setCustomStyleError('');
        customStyleApi('/v1/styles/delete', { method: 'POST', body: JSON.stringify({ id: preset.serverId }) })
            .then(function () {
                if (editingCustomStyleId === styleId) { editingCustomStyleId = null; clearCustomStyleForm(); }
                return refreshCustomStyles().then(function () {
                    /* 如果当前正用着被删的画风，退回第一个内置画风 */
                    if (settings.stylePreset === styleId) {
                        settings.stylePreset = baseStylePresets[0].id;
                        saveSettings();
                        renderStylePresetSelect();
                    }
                    showToast('success', '画风已删除');
                });
            })
            .catch(function (error) {
                setCustomStyleError((error && error.message) || '删除失败，请重试');
            });
    }

    function bindCustomStyleEvents() {
        $('#cpab-custom-save').off('click.cpabCustom').on('click.cpabCustom', saveCustomStyle);
        $('#cpab-custom-reset').off('click.cpabCustom').on('click.cpabCustom', clearCustomStyleForm);
        $('#cpab-custom-reload').off('click.cpabCustom').on('click.cpabCustom', function () {
            setCustomStyleTip('正在从服务器重新读取…');
            refreshCustomStyles().then(function (list) {
                setCustomStyleTip('已同步，共 ' + list.length + ' 个自定义画风');
            });
        });
        $('#cpab-custom-name').off('input.cpabCustom').on('input.cpabCustom', function () {
            if (editingCustomStyleId) { syncCustomStyleMode(); }
        });
    }

    function applyStylePresetSelection(presetId) {
        settings.stylePreset = normalizeStylePreset(presetId);
        saveSettings();
        syncStylePresetControls();
        var selectedUi = getStylePresetUi(settings.stylePreset);
        setStatus('画风已切换为“' + selectedUi.label + '”，下次生图自动使用');
        showToast('success', '已选择画风：' + selectedUi.label);
    }

    function collectSettingsFromUi() {
        settings.apiUrl = normalizeApiUrl($('#cpab-api-url').val());
        settings.apiKey = String($('#cpab-api-key').val() || '').trim();
        settings.resolution = normalizeResolution($('#cpab-resolution').val());
        settings.steps = normalizeSteps($('#cpab-steps').val());
        settings.autoGenerate = $('#cpab-auto-generate').is(':checked');
        settings.stylePreset = normalizeStylePreset(settings.stylePreset);
    }

    function bindSettingsEvents() {
        $('#cpab-style-select').on('change', function () {
            applyStylePresetSelection($(this).val());
        });
        /* 自定义画风区的按钮与输入 */
        bindCustomStyleEvents();
        // 切换分辨率时立刻刷新消耗提示（高清档慢约 10 秒、扣 2 次）
        $('#cpab-resolution').on('change', function () {
            collectSettingsFromUi();
            renderResolutionNote();
            refreshButtons();
        });
        $('#cpab-check-update').on('click', function () {
            if (updaterState.available) performExtensionUpdate();
            else checkForUpdates(true);
        });
        $('#cpab-save').on('click', async function () {
            collectSettingsFromUi();
            saveSettings();
            refreshButtons();
            if (settings.autoGenerate) scheduleAutoGenerate('SETTINGS_SAVED');
            try {
                if (settings.apiKey) await Promise.all([refreshQuota(true), refreshQueueStatus(true)]);
                setStatus(settings.apiKey ? '设置已保存' : '设置已保存，请点击领取免费50次；用完后加QQ群联系群主购买卡密');
                showToast('success', '默默画图设置已保存');
            } catch (error) {
                setStatus('保存后连接失败：' + (error.message || error));
                showToast('error', error.message || String(error));
            }
        });
        $('#cpab-claim-trial').on('click', async function () {
            var $button = $(this);
            var currentKey = String($('#cpab-api-key').val() || settings.apiKey || '').trim();
            if (/^trial_/i.test(currentKey)) {
                showTrialAlreadyClaimedNotice();
                setStatus('本机已经领取过免费50次额度');
                return;
            }
            if (currentKey) {
                showToast('warning', '当前已有购买卡密，不会用免费卡覆盖');
                return;
            }
            $button.prop('disabled', true).addClass('is-loading');
            try {
                await refreshDiscoveredApiUrl(true, true);
                var data = await claimTrialKey(requireApiUrl(), false);
                if (data && data.created) {
                    await Promise.all([refreshQuota(true), refreshQueueStatus(true)]);
                }
            } catch (error) {
                setStatus('免费额度领取失败：' + (error.message || error));
                showToast('error', error.message || String(error));
                if (Number(error.status) === 429) showTrialAlreadyClaimedNotice();
            } finally {
                $button.prop('disabled', false).removeClass('is-loading');
            }
        });
        $('#cpab-check-quota').on('click', async function () {
            collectSettingsFromUi();
            saveSettings();
            try {
                await Promise.all([refreshQuota(false), refreshQueueStatus(false)]);
                setStatus('额度和服务器队列查询成功');
            } catch (error) {
                setStatus('查询失败：' + (error.message || error));
            }
        });
        // ---------------- 充值入口 ----------------
        // 插件不重复实现支付界面，直接打开网页版充值页（同一套后端）
        $('#cpab-open-recharge').on('click', async function () {
            var base = '';
            try {
                await refreshDiscoveredApiUrl(true, true);
                base = requireApiUrl();
            } catch (error) {
                base = normalizeApiUrl(settings.apiUrl);
            }
            if (!base) {
                showToast('error', '还没有拿到服务器地址，请稍后再试');
                return;
            }
            var url = base + '/?recharge=1';
            window.open(url, '_blank', 'noopener');
            setStatus('已在新标签页打开充值页面，付款后在页面里点「我已付款」即可');
        });
        // 拿到新卡密时一键粘贴进来（老用户加次数不需要换卡，用不到这个）
        $('#cpab-paste-key').on('click', async function () {
            var text = '';
            try {
                text = await navigator.clipboard.readText();
            } catch (error) {
                showToast('error', '浏览器不允许读取剪贴板，请手动粘贴到上面的卡密输入框');
                return;
            }
            var key = String(text || '').trim();
            if (!/^(img_|trial_)[A-Za-z0-9_-]{6,}$/.test(key)) {
                showToast('error', '剪贴板里不是有效的卡密，请先复制卡密再点这里');
                return;
            }
            $('#cpab-api-key').val(key);
            collectSettingsFromUi();
            saveSettings();
            showToast('success', '新卡密已填入并保存');
            try { await Promise.all([refreshQuota(false), refreshQueueStatus(false)]); } catch (error) { /* 忽略查询失败 */ }
        });
        $('#cpab-toggle-key').on('click', function () {
            var $key = $('#cpab-api-key');
            var visible = $key.attr('type') === 'text';
            $key.attr('type', visible ? 'password' : 'text');
            $(this).find('i').toggleClass('fa-eye', visible).toggleClass('fa-eye-slash', !visible);
        });
    }

    function bindGlobalEvents() {
        $(document).off('click.cpabGenerate').on('click.cpabGenerate', '.cpab-mes-button', function (event) { handleGenerateClick(event, 'normal'); });
        $(document).off('click.cpabRandom').on('click.cpabRandom', '.cpab-random-button', function (event) { handleGenerateClick(event, 'random'); });
        $(document).off('click.cpabOptimize').on('click.cpabOptimize', '.cpab-optimize-button', function (event) { handleGenerateClick(event, 'optimize'); });
        $(document).off('change.cpabInlineStyle').on('change.cpabInlineStyle', '.cpab-inline-style-select', function () {
            applyStylePresetSelection($(this).val());
        });
        var eventSource = window.eventSource || (window.SillyTavern && window.SillyTavern.eventSource);
        var eventTypes = window.event_types || (window.SillyTavern && window.SillyTavern.event_types) || {};
        if (eventSource && eventSource.on) {
            if (eventTypes.CHARACTER_MESSAGE_RENDERED) eventSource.on(eventTypes.CHARACTER_MESSAGE_RENDERED, function (messageId) {
                ensureButtonForMessage(messageId);
                scheduleAutoGenerate('CHARACTER_MESSAGE_RENDERED');
            });
            if (eventTypes.CHAT_CHANGED) eventSource.on(eventTypes.CHAT_CHANGED, function () {
                refreshButtons();
                scheduleAutoGenerate('CHAT_CHANGED');
            });
            if (eventTypes.MESSAGE_SWIPED) eventSource.on(eventTypes.MESSAGE_SWIPED, function () {
                refreshButtons();
                scheduleAutoGenerate('MESSAGE_SWIPED');
            });
            if (eventTypes.MESSAGE_UPDATED) eventSource.on(eventTypes.MESSAGE_UPDATED, function () {
                refreshButtons();
                scheduleAutoGenerate('MESSAGE_UPDATED');
            });
            if (eventTypes.MESSAGE_DELETED) eventSource.on(eventTypes.MESSAGE_DELETED, refreshButtons);
        }
        setInterval(refreshButtons, 3000);
        setInterval(function () { refreshQueueStatus(true).catch(function () {}); }, 2000);
        setInterval(function () {
            if (settings.autoGenerate) checkAutoGenerate('POLLING_INTERVAL').catch(function () {});
        }, 2000);
    }

    try {
        var settingsHtml = await $.get(extensionFolderPath + '/settings.html');
        $('#extensions_settings2').append(settingsHtml);
        loadSettingsToUi();
        bindSettingsEvents();
        bindGlobalEvents();
        refreshButtons();
        scheduleAutoGenerate('INIT');
        setTimeout(function () { checkForUpdates(false); }, 1800);
        try {
            await refreshDiscoveredApiUrl(true, false);
        } catch (error) {
            setStatus('最新地址获取失败，将尝试已保存地址：' + (error.message || error));
        }
        if (settings.apiUrl && settings.apiKey) {
            try {
                await Promise.all([refreshQuota(true), refreshQueueStatus(true)]);
            } catch (error) {
                setStatus('卡密连接失败：' + (error.message || error));
            }
        } else {
            setStatus('请点击领取免费50次；免费额度用完后，请加QQ群联系群主购买卡密');
        }
        console.log('[' + extensionName + '] loaded');
    } catch (error) {
        console.error('[' + extensionName + '] init failed', error);
        showToast('error', '插件初始化失败：' + (error.message || error));
    }
});
