// @ts-nocheck
jQuery(async function () {
    'use strict';

    var extensionName = 'comfyui-public-api-button';
    var extensionFolderPath = '/scripts/extensions/third-party/' + extensionName;
    var endpointDiscoveryUrl = 'https://momo-draw-endpoint.1830488003.workers.dev/v1/endpoint';
    var endpointDiscoveryIntervalMs = 30000;
    var updaterRepoOwner = '1830488003';
    var updaterRepoName = 'comfyui-public-api-button';
    var storageKey = 'comfyui_public_api_button_settings';
    var autoGeneratedStorageKey = 'comfyui_public_api_button_auto_generated';
    var allowedResolutions = ['512x768', '512x512', '768x512'];
    var allowedSteps = [4, 6, 8];
    var stylePresets = [
        { id: 'genshin-open-world', name: '原神感开放世界', label: '原神感开放世界', description: '明亮幻想世界、元素特效和精致二次元角色。', promptTitle: '原神感开放世界二次元游戏主视觉', prefix: '精致的开放世界幻想二次元游戏插画，鲜明的元素特效，华丽的角色服装，明亮的幻想景色', suffix: '干净的赛璐璐上色，繁复细节，电影感角色宣传图，色彩鲜艳的高级游戏视觉', prefixWeight: 1.45, suffixWeight: 1.30 },
        { id: 'arknights-tactical', name: '明日方舟感战术二次元', label: '明日方舟感战术二次元', description: '冷色战术服、末世城市和高级二游宣传图。', promptTitle: '明日方舟感战术二次元风格', prefix: '暗色战术二次元游戏美术，末世都市，机能风干员服装，工业科幻环境', suffix: '低饱和色彩配合醒目点缀色，平面设计构图，电影轮廓光，高级手游主视觉', prefixWeight: 1.45, suffixWeight: 1.30 },
        { id: 'gacha-character-splash', name: '热门二游角色立绘', label: '热门二游角色立绘', description: '通用高质量二游立绘，适合角色和技能特效。', promptTitle: '热门二游角色立绘风格', prefix: '高级二次元游戏角色插画，全身英雄姿态，繁复服装，强烈魔法特效', suffix: '动感构图，精致赛璐璐上色，细腻配饰，商业手游角色宣传图', prefixWeight: 1.42, suffixWeight: 1.28 },
        { id: 'donghua-3d-character', name: '国漫3D角色', label: '国漫3D角色', description: '国漫三维角色、精致建模和仙侠电影光影。', promptTitle: '国漫三维角色风格', prefix: '国风三维动画角色，精致五官，细腻头发和服装，电影感幻想环境', suffix: '高级动画电影渲染，柔和皮肤明暗，戏剧性光线，精致国风幻想视觉', prefixWeight: 1.40, suffixWeight: 1.28 },
        { id: 'kpop-idol-concept', name: '韩国女团概念照', label: '韩国女团概念照', description: '女团回归海报、舞台妆造和杂志级灯光。', promptTitle: '韩国女团概念照风格', prefix: '高级韩国偶像概念摄影，精致美妆造型，协调统一的舞台服装，自信表演姿态', suffix: '亮泽杂志灯光，干净皮肤质感，时尚妆容，高级回归预告片氛围', prefixWeight: 1.40, suffixWeight: 1.28 },
        { id: 'korean-clean-girl', name: '韩系清冷女友感', label: '韩系清冷女友感', description: '清冷自然、干净妆面和柔和生活感。', promptTitle: '韩系清冷女友感风格', prefix: '极简韩系时尚人像，清冷优雅的年轻女性，干净妆容，柔和中性色服装，安静亲密氛围', suffix: '明亮漫射日光，自然皮肤纹理，克制调色，细腻生活方式摄影', prefixWeight: 1.38, suffixWeight: 1.25 },
        { id: 'douyin-fashion', name: '抖音爆款穿搭', label: '抖音爆款穿搭', description: '熟悉的抖音穿搭、显身材构图和抓眼配色。', promptTitle: '抖音爆款穿搭风格', prefix: '流行中文社交媒体时尚摄影，抓眼穿搭，自信姿态，时髦都市地点', suffix: '显气色的光线，适合手机观看的构图，干净鲜明调色，爆款穿搭短视频封面观感', prefixWeight: 1.40, suffixWeight: 1.28 },
        { id: 'y2k-streetwear', name: 'Y2K辣妹街拍', label: 'Y2K辣妹街拍', description: '千禧辣妹、闪光灯街拍和韩系潮流。', promptTitle: '千禧辣妹街拍风格', prefix: '千禧年街头穿搭人像，修身短上衣，金属配饰，低腰造型，俏皮自信姿态', suffix: '直打闪光灯，霓虹城市细节，亮泽时尚杂志色彩，世纪初流行文化氛围', prefixWeight: 1.40, suffixWeight: 1.28 },
        { id: 'dopamine-fashion', name: '多巴胺穿搭', label: '多巴胺穿搭', description: '高饱和撞色、活力穿搭和明快社交媒体观感。', promptTitle: '多巴胺穿搭风格', prefix: '大胆彩色时尚人像，活泼叠穿，高饱和撞色，快乐有活力的姿态', suffix: '明亮日光，干净商业构图，鲜艳社交媒体调色，轻快潮流造型', prefixWeight: 1.38, suffixWeight: 1.25 },
        { id: 'old-money-glamour', name: '千金老钱风', label: '千金老钱风', description: '克制奢华、富家千金和高级杂志质感。', promptTitle: '千金老钱风', prefix: '低调奢华人像，优雅剪裁服装，精致富裕氛围，经典高级室内环境', suffix: '柔和杂志灯光，克制中性色调，高级面料纹理，永不过时的时尚摄影', prefixWeight: 1.38, suffixWeight: 1.25 },
        { id: 'guochao-streetwear', name: '国潮街头', label: '国潮街头', description: '传统纹样加现代街头服装，辨识度强。', promptTitle: '现代国潮街头风格', prefix: '传统中式纹样与现代都市服装结合，大胆图形设计，自信年轻姿态', suffix: '红黑金点缀，当代城市背景，商业广告灯光，鲜明中国潮流身份', prefixWeight: 1.42, suffixWeight: 1.28 },
        { id: 'new-chinese-chic', name: '新中式穿搭', label: '新中式穿搭', description: '日常能穿的新中式，不是古装影楼感。', promptTitle: '现代新中式穿搭风格', prefix: '当代中式灵感服装，优雅立领与流动面料，含蓄传统细节，现代日常造型', suffix: '雅致东方配色，柔和电影光线，高级时尚杂志质感，干净从容构图', prefixWeight: 1.42, suffixWeight: 1.28 },
        { id: 'hanfu-cinematic', name: '汉服仙侠大片', label: '汉服仙侠大片', description: '汉服、仙侠场景、飘带和电影海报光影。', promptTitle: '电影感汉服仙侠风格', prefix: '宏大中式幻想场景中的优雅汉服角色，飘动宽袖，精致发饰，浪漫英雄氛围', suffix: '云雾山川，戏剧性逆光，丰富面料细节，电影感武侠幻想海报', prefixWeight: 1.42, suffixWeight: 1.30 },
        { id: 'xiaohongshu-lifestyle', name: '小红书氛围感', label: '小红书氛围感', description: '咖啡店、旅行和日常生活里的精致氛围。', promptTitle: '小红书氛围感摄影风格', prefix: '精致中文生活方式照片，时髦年轻人物，有品位的咖啡店或旅行地点，放松自然姿态', suffix: '柔和窗边光，温暖干净调色，精心安排的日常细节，高级社交媒体审美', prefixWeight: 1.38, suffixWeight: 1.25 },
        { id: 'phone-flash-candid', name: '手机闪光灯随拍', label: '手机闪光灯随拍', description: '像朋友手机拍的夜间闪光随拍，真实又时髦。', promptTitle: '手机直闪随拍风格', prefix: '随意手持手机快照，自发自然姿态，正面直打闪光灯，真实日常地点', suffix: '轻微运动柔化，自然皮肤纹理，不完美取景，潮流夜生活社交照片氛围', prefixWeight: 1.38, suffixWeight: 1.25 },
        { id: 'korean-webtoon', name: '韩漫恋爱感', label: '韩漫恋爱感', description: '韩漫俊男美女、恋爱氛围和精致条漫上色。', promptTitle: '韩漫恋爱插画风格', prefix: '漂亮韩漫角色，时髦现代服装，浪漫情绪互动，干净优雅线稿', suffix: '柔和渐变上色，精致有吸引力的表情，电影分镜构图，高级恋爱条漫审美', prefixWeight: 1.42, suffixWeight: 1.28 },
        { id: 'cosplay-realism', name: '高还原COS写真', label: '高还原COS写真', description: '把二游角色变成高还原真人COS宣传照。', promptTitle: '高还原游戏角色扮演写真风格', prefix: '高度还原热门幻想游戏角色的真人扮演，精细服装和道具，符合角色性格的姿态', suffix: '电影感实景灯光，真实布料与盔甲纹理，高规格造型，精致宣传写真', prefixWeight: 1.40, suffixWeight: 1.28 },
        { id: 'blindbox-3d', name: '潮玩盲盒3D', label: '潮玩盲盒3D', description: '潮玩手办、盲盒比例和商品宣传渲染。', promptTitle: '潮玩盲盒三维渲染风格', prefix: '可爱收藏级设计师潮玩，圆润迷你比例，生动表情，时髦微型服装', suffix: '高级搪胶材质，干净影棚灯光，彩色商品陈列，精致盲盒宣传渲染', prefixWeight: 1.40, suffixWeight: 1.28 },
        { id: 'cinematic-photo', name: 'Cinematic Photo', promptTitle: '电影感摄影风格', prefix: '电影感照片，自然光照', suffix: '高反差，专业摄影质感，清晰对焦，浅景深' },
        { id: 'medium-format', name: 'Medium Format', promptTitle: '中画幅胶片风格', prefix: '中画幅胶片照片，电影剧照氛围', suffix: '电影轮廓光，柔和胶片颗粒，柯达波特拉色调' },
        { id: 'analog-film', name: 'Analog Film', promptTitle: '复古模拟胶片风格', prefix: '模拟胶片照片，颗粒纹理，暖色偏移，轻微暗角', suffix: '复古胶片质感，细腻颗粒，褪色高光，柔和阴影' },
        { id: 'point-and-shoot-candid', name: 'Point-and-Shoot Candid', promptTitle: '随手抓拍风格', prefix: '便携相机自然抓拍，手持拍摄的不完美感', suffix: '轻微运动柔化，机顶闪光灯衰减，未经摆拍的纪实感' },
        { id: 'ansel-adams-landscape', name: 'Ansel Adams Landscape', promptTitle: '亚当斯黑白风景风格', prefix: '高反差大画幅黑白风景，强烈明暗层次', suffix: '区域曝光，锐利前景细节，永恒黑白质感，细腻颗粒写实' },
        { id: 'film-noir', name: 'Film Noir', promptTitle: '黑色电影风格', prefix: '黑色电影美学，黑白色调，强烈反差，阴郁方向性阴影', suffix: '二十世纪四十年代氛围，神秘电影光线，深黑层次' },
        { id: 'neon-noir', name: 'Neon Noir', promptTitle: '霓虹黑色电影风格', prefix: '霓虹黑色电影，雨夜街道，赛博未来气息', suffix: '发光招牌，高反差，低照度，积水反射' },
        { id: 'cyberpunk', name: 'Cyberpunk', promptTitle: '赛博朋克风格', prefix: '霓虹笼罩的赛博未来，密集全息影像，雨夜街道', suffix: '发光电子线路，反光表面，强烈电气氛围' },
        { id: 'solarpunk', name: 'Solarpunk', promptTitle: '太阳朋克风格', prefix: '明亮太阳朋克乌托邦，有机建筑，繁茂绿植与科技融合', suffix: '阳光照耀的可再生能源系统，和谐生态设计，柔和乐观色调' },
        { id: 'dieselpunk', name: 'Dieselpunk', promptTitle: '柴油朋克风格', prefix: '柴油朋克复古工业美学，厚重的二十世纪三十年代机械', suffix: '粗粝油污纹理，黄铜配件，烟雾弥漫' },
        { id: 'steampunk', name: 'Steampunk', promptTitle: '蒸汽朋克风格', prefix: '蒸汽朋克美学，黄铜机械，维多利亚工业氛围', suffix: '齿轮，铆钉，暖色古董金属色调，繁复细节' },
        { id: 'epic-concept-art', name: 'Epic Concept Art', promptTitle: '史诗概念艺术风格', prefix: '电影级大型游戏概念艺术，辽阔景观，细致建筑结构', suffix: '英雄式构图，大气纵深，极度精致的商业渲染' },
        { id: 'ethereal-fantasy', name: 'Ethereal Fantasy', promptTitle: '空灵幻想风格', prefix: '空灵幻想概念艺术', suffix: '宏伟，圣洁，绘画感，史诗，庄严，梦幻封面艺术' },
        { id: 'dark-fantasy-painterly', name: 'Dark Fantasy Painterly', promptTitle: '暗黑幻想绘画风格', prefix: '暗黑高级幻想数字绘画，压抑深沉氛围', suffix: '戏剧性阴影，神秘光线，细腻丰富的环境绘制' },
        { id: 'ghibli-inspired', name: 'Ghibli-Inspired', promptTitle: '吉卜力动画风格', prefix: '吉卜力感手绘二维动画，温柔奇幻的日式动画电影美学，简洁生动的动漫人物设计', suffix: '赛璐璐手绘背景，干净动漫五官，柔和绘画光线，温暖配色，繁茂环境细节，明确的非写实插画', prefixWeight: 1.45, suffixWeight: 1.35 },
        { id: 'dark-moebius', name: 'Dark Moebius', promptTitle: '暗黑莫比乌斯幻想风格', prefix: '图像化超现实幻想，锐利线条，梦境般建筑', suffix: '有限色板，棱角构图，诡异紧张的空气感' },
        { id: 'comic-book', name: 'Comic Book', promptTitle: '美式漫画风格', prefix: '西方漫画风格，强烈墨线轮廓，大胆平面图形', suffix: '网点阴影，鲜明纯色，动感英雄式构图' },
        { id: 'manga', name: 'Manga', promptTitle: '黑白漫画风格', prefix: '黑白漫画插画，强烈勾线，分镜式反差', suffix: '网点纸阴影，风格化表情，动感速度线' },
        { id: 'anime-key-visual', name: 'Anime Key Visual', promptTitle: '动漫主视觉风格', prefix: '动画作品主视觉，专业动画海报', suffix: '鲜艳色彩，高细节赛璐璐上色，情绪化构图' },
        { id: '90s-ova-anime', name: '90s OVA Anime', promptTitle: '二十世纪九十年代动画录像带风格', prefix: '二十世纪九十年代动画录像带美学，清晰赛璐璐轮廓，复古配色', suffix: '胶片颗粒纹理，戏剧性高光，怀旧阴影' },
        { id: 'pixel-art', name: 'Pixel Art', promptTitle: '像素画风格', prefix: '复古像素插画，清晰像素网格', suffix: '有限色板，十六位游戏美学，怀旧电子游戏风格' },
        { id: 'watercolor', name: 'Watercolor', promptTitle: '水彩画风格', prefix: '水彩绘画，松散笔触，颜料自然晕染', suffix: '鲜艳，绘画感，丰富肌理，柔和纸张纹理' },
        { id: 'stained-glass', name: 'Stained Glass', promptTitle: '彩色玻璃风格', prefix: '彩色玻璃美学，铅条轮廓，半透明色块', suffix: '鲜艳背光，繁复细节，教堂花窗氛围' },
        { id: 'art-deco', name: 'Art Deco', promptTitle: '装饰艺术风格', prefix: '装饰艺术美学，几何形状，大胆对称', suffix: '奢华金色点缀，华丽装饰细节' },
        { id: 'tilt-shift', name: 'Tilt Shift', promptTitle: '移轴微缩摄影风格', prefix: '移轴摄影，选择性对焦，微缩模型效果', suffix: '背景虚化，鲜艳饱和度，玩具场景观感' }
    ];
    var stylePresetUi = {
        'genshin-open-world': { label: '原神感开放世界', group: '🔥 热门潮流', description: '明亮幻想世界、元素特效和精致二次元角色。' },
        'arknights-tactical': { label: '明日方舟感战术二次元', group: '🔥 热门潮流', description: '冷色战术服、末世城市和高级二游宣传图。' },
        'gacha-character-splash': { label: '热门二游角色立绘', group: '🔥 热门潮流', description: '通用高质量二游立绘，适合角色和技能特效。' },
        'donghua-3d-character': { label: '国漫三维角色', group: '🔥 热门潮流', description: '精致三维建模、国风角色和仙侠电影光影。' },
        'kpop-idol-concept': { label: '韩国女团概念照', group: '🔥 热门潮流', description: '女团回归海报、舞台妆造和杂志级灯光。' },
        'korean-clean-girl': { label: '韩系清冷女友感', group: '🔥 热门潮流', description: '清冷自然、干净妆面和柔和生活感。' },
        'douyin-fashion': { label: '抖音爆款穿搭', group: '🔥 热门潮流', description: '熟悉的抖音穿搭、显身材构图和抓眼配色。' },
        'y2k-streetwear': { label: '千禧辣妹街拍', group: '🔥 热门潮流', description: '千禧辣妹、闪光灯街拍和韩系潮流。' },
        'dopamine-fashion': { label: '多巴胺穿搭', group: '🔥 热门潮流', description: '高饱和撞色、活力穿搭和明快社交媒体观感。' },
        'old-money-glamour': { label: '千金老钱风', group: '🔥 热门潮流', description: '克制奢华、富家千金和高级杂志质感。' },
        'guochao-streetwear': { label: '国潮街头', group: '🔥 热门潮流', description: '传统纹样加现代街头服装，辨识度强。' },
        'new-chinese-chic': { label: '新中式穿搭', group: '🔥 热门潮流', description: '日常能穿的新中式，不是古装影楼感。' },
        'hanfu-cinematic': { label: '汉服仙侠大片', group: '🔥 热门潮流', description: '汉服、仙侠场景、飘带和电影海报光影。' },
        'xiaohongshu-lifestyle': { label: '小红书氛围感', group: '🔥 热门潮流', description: '咖啡店、旅行和日常生活里的精致氛围。' },
        'phone-flash-candid': { label: '手机闪光灯随拍', group: '🔥 热门潮流', description: '像朋友手机拍的夜间闪光随拍，真实又时髦。' },
        'korean-webtoon': { label: '韩漫恋爱感', group: '🔥 热门潮流', description: '韩漫俊男美女、恋爱氛围和精致条漫上色。' },
        'cosplay-realism': { label: '高还原角色扮演写真', group: '🔥 热门潮流', description: '把二游角色变成高还原真人角色扮演宣传照。' },
        'blindbox-3d': { label: '潮玩盲盒三维', group: '🔥 热门潮流', description: '潮玩手办、盲盒比例和商品宣传渲染。' },
        'cinematic-photo': { label: '电影感摄影', group: '摄影写实', description: '自然光、强对比、专业摄影质感和浅景深。' },
        'medium-format': { label: '中画幅胶片', group: '摄影写实', description: '电影剧照般的中画幅胶片质感，柔和颗粒和柯达色调。' },
        'analog-film': { label: '复古模拟胶片', group: '摄影写实', description: '温暖偏色、轻微暗角、褪色高光和复古胶片颗粒。' },
        'point-and-shoot-candid': { label: '随手抓拍', group: '摄影写实', description: '手持相机的自然抓拍感，轻微运动模糊和闪光灯效果。' },
        'ansel-adams-landscape': { label: '亚当斯黑白风景', group: '摄影写实', description: '高反差大画幅黑白风景，前景锐利、层次丰富。' },
        'film-noir': { label: '黑色电影', group: '摄影写实', description: '1940年代黑白电影氛围，深黑阴影和神秘方向光。' },
        'tilt-shift': { label: '移轴微缩摄影', group: '摄影写实', description: '选择性对焦和微缩模型效果，色彩鲜明、背景虚化。' },
        'neon-noir': { label: '霓虹黑色电影', group: '科幻与复古未来', description: '雨夜街道、霓虹招牌、低光高反差和湿地反射。' },
        'cyberpunk': { label: '赛博朋克', group: '科幻与复古未来', description: '密集霓虹、全息影像、电子线路和未来都市氛围。' },
        'solarpunk': { label: '太阳朋克', group: '科幻与复古未来', description: '绿色植物与科技共生的明亮未来，环保、温暖、乐观。' },
        'dieselpunk': { label: '柴油朋克', group: '科幻与复古未来', description: '1930年代重工业机械、油污纹理、黄铜和烟雾。' },
        'steampunk': { label: '蒸汽朋克', group: '科幻与复古未来', description: '维多利亚工业风、齿轮铆钉和暖色古铜机械。' },
        'art-deco': { label: '装饰艺术', group: '科幻与复古未来', description: '几何造型、强烈对称和华丽金色装饰。' },
        'epic-concept-art': { label: '史诗概念设计', group: '幻想与概念艺术', description: '宏大场景、英雄构图、空间纵深和游戏概念设计质感。' },
        'ethereal-fantasy': { label: '空灵幻想', group: '幻想与概念艺术', description: '梦幻、神圣、宏伟的绘画感幻想封面风格。' },
        'dark-fantasy-painterly': { label: '暗黑幻想绘画', group: '幻想与概念艺术', description: '阴郁的高幻想氛围、戏剧阴影和神秘光线。' },
        'ghibli-inspired': { label: '吉卜力灵感', group: '幻想与概念艺术', description: '温暖手绘故事感、柔和光线和茂盛环境细节。' },
        'dark-moebius': { label: '暗黑莫比乌斯', group: '幻想与概念艺术', description: '超现实建筑、硬朗线条、有限色彩和诡异梦境感。' },
        'anime-key-visual': { label: '动漫主视觉', group: '动漫与漫画', description: '鲜艳细致的动画主视觉，赛璐璐上色和情绪化构图。' },
        '90s-ova-anime': { label: '90年代OVA动漫', group: '动漫与漫画', description: '复古动画配色、清晰赛璐璐轮廓和怀旧胶片颗粒。' },
        'manga': { label: '日式黑白漫画', group: '动漫与漫画', description: '黑白墨线、网点阴影、夸张表情和动态速度线。' },
        'comic-book': { label: '美式漫画', group: '动漫与漫画', description: '粗壮墨线、鲜明平涂、网点阴影和英雄式构图。' },
        'pixel-art': { label: '像素艺术', group: '艺术与特殊效果', description: '清晰像素格、有限色板和16位复古游戏质感。' },
        'watercolor': { label: '水彩画', group: '艺术与特殊效果', description: '松散笔触、颜料晕染、鲜活色彩和纸张纹理。' },
        'stained-glass': { label: '彩色玻璃', group: '艺术与特殊效果', description: '铅条分割、半透明色块和教堂窗户般的背光。' }
    };
    var defaultSettings = {
        apiUrl: 'https://magic-arthritis-maintain-altered.trycloudflare.com',
        apiKey: '',
        installId: '',
        resolution: '768x512',
        steps: 4,
        autoGenerate: false,
        stylePreset: 'anime-key-visual'
    };
    var contextGetter = function () {
        return window.SillyTavern && window.SillyTavern.getContext
            ? window.SillyTavern.getContext()
            : null;
    };
    var extensionSettingsRoot = window.extension_settings || {};
    extensionSettingsRoot[extensionName] = extensionSettingsRoot[extensionName] || {};
    var lastQueueAhead = 0;
    var queueState = 'offline';
    var queuePollBusy = false;
    var trialClaimPromise = null;
    var purchaseNoticeShown = false;
    var endpointDiscoveryPromise = null;
    var lastEndpointDiscoveryAt = 0;
    var autoGenerateTimer = null;
    var autoGeneratePollingBusy = false;
    var autoGenerateInFlight = new Set();
    var autoGenerateRetryAfter = new Map();
    var updaterState = {
        currentVersion: '0.0.0',
        latestVersion: '0.0.0',
        available: false,
        checking: false,
        updating: false,
        notifiedVersion: ''
    };

    function loadLocalSettings() {
        try {
            return JSON.parse(localStorage.getItem(storageKey) || '{}') || {};
        } catch (error) {
            console.warn('[' + extensionName + '] settings parse failed', error);
            return {};
        }
    }

    function normalizeSteps(value) {
        var numeric = Number(value);
        return allowedSteps.indexOf(numeric) >= 0 ? numeric : defaultSettings.steps;
    }

    function normalizeResolution(value) {
        var text = String(value || '');
        return allowedResolutions.indexOf(text) >= 0 ? text : defaultSettings.resolution;
    }

    function getStylePreset(value) {
        var presetId = String(value || '');
        return stylePresets.find(function (preset) { return preset.id === presetId; })
            || stylePresets.find(function (preset) { return preset.id === defaultSettings.stylePreset; })
            || stylePresets[0];
    }

    function normalizeStylePreset(value) {
        return getStylePreset(value).id;
    }

    function getStylePresetUi(value) {
        var preset = getStylePreset(value);
        return stylePresetUi[preset.id] || { label: preset.name, group: '其他', description: '插件将自动补充对应的画风和质量提示词。' };
    }

    function buildStyledPrompt(scenePrompt, presetId) {
        var preset = getStylePreset(presetId);
        var prefixWeight = Number(preset.prefixWeight) || 1.35;
        var suffixWeight = Number(preset.suffixWeight) || 1.25;
        var presetUi = stylePresetUi[preset.id] || {};
        var promptTitle = String(preset.promptTitle || presetUi.label || preset.name).trim();
        var weightedPrefix = '(' + promptTitle + ', ' + preset.prefix + ':' + prefixWeight.toFixed(2) + ')';
        var weightedSuffix = '(' + preset.suffix + ':' + suffixWeight.toFixed(2) + ')';
        return [weightedPrefix, String(scenePrompt || '').trim(), weightedSuffix]
            .filter(Boolean)
            .join(', ');
    }

    var settings = Object.assign({}, defaultSettings, loadLocalSettings(), extensionSettingsRoot[extensionName]);
    settings.resolution = normalizeResolution(settings.resolution);
    settings.steps = normalizeSteps(settings.steps);
    settings.autoGenerate = Boolean(settings.autoGenerate);
    settings.stylePreset = normalizeStylePreset(settings.stylePreset);
    Object.assign(extensionSettingsRoot[extensionName], settings);

    function loadAutoGeneratedMap() {
        try {
            return JSON.parse(localStorage.getItem(autoGeneratedStorageKey) || '{}') || {};
        } catch (error) {
            console.warn('[' + extensionName + '] auto generation record parse failed', error);
            return {};
        }
    }

    function saveAutoGeneratedMap(map) {
        try {
            localStorage.setItem(autoGeneratedStorageKey, JSON.stringify(map || {}));
        } catch (error) {
            console.warn('[' + extensionName + '] auto generation record save failed', error);
        }
    }

    function getChatKey() {
        var context = contextGetter();
        return String(
            (context && (context.chatId || context.groupId || context.name2 || context.characterName))
            || 'unknown_chat'
        );
    }

    function getLastAiMessageIndex() {
        var context = contextGetter();
        var chat = context && Array.isArray(context.chat) ? context.chat : [];
        for (var index = chat.length - 1; index >= 0; index--) {
            if (chat[index] && !chat[index].is_user) return index;
        }
        return null;
    }

    function markMessageGenerated(messageId, prompt) {
        var chatKey = getChatKey();
        var map = loadAutoGeneratedMap();
        map[chatKey] = map[chatKey] || {};
        map[chatKey][String(messageId)] = prompt;
        saveAutoGeneratedMap(map);
    }

    function scheduleAutoGenerate(reason) {
        if (!settings.autoGenerate || !settings.apiKey) return;
        if (autoGenerateTimer) clearTimeout(autoGenerateTimer);
        autoGenerateTimer = setTimeout(function () {
            checkAutoGenerate(reason || '').catch(function (error) {
                console.warn('[' + extensionName + '] auto generation failed', error);
            });
        }, 1200);
    }

    async function checkAutoGenerate(reason) {
        if (!settings.autoGenerate || !settings.apiKey || autoGeneratePollingBusy) return;
        autoGeneratePollingBusy = true;
        try {
            var context = contextGetter();
            var chat = context && Array.isArray(context.chat) ? context.chat : [];
            var messageId = getLastAiMessageIndex();
            if (typeof messageId !== 'number') return;
            var message = chat[messageId];
            if (!message || message.is_user) return;

            var prompt;
            try {
                prompt = extractImagePrompt(message.mes);
            } catch (error) {
                return;
            }

            var chatKey = getChatKey();
            var map = loadAutoGeneratedMap();
            var previousPrompt = (message.extra && message.extra.cpab_auto_generated_prompt)
                || (map[chatKey] && map[chatKey][String(messageId)]);
            if (previousPrompt === prompt) return;

            var inFlightKey = chatKey + '::' + messageId + '::' + prompt;
            if (autoGenerateInFlight.has(inFlightKey)) return;
            if (Number(autoGenerateRetryAfter.get(inFlightKey) || 0) > Date.now()) return;

            autoGenerateInFlight.add(inFlightKey);
            try {
                ensureButtonForMessage(messageId);
                var $button = $('.cpab-mes-button[data-cpab-mesid="' + messageId + '"]').first();
                setStatus('检测到新楼层绘画提示词，正在自动生图...');
                await generateForMessage(messageId, $button.length ? $button : null, 'normal');
                autoGenerateRetryAfter.delete(inFlightKey);
            } catch (error) {
                autoGenerateRetryAfter.set(inFlightKey, Date.now() + 15000);
                setStatus('自动生图失败，15秒后重试：' + (error.message || error));
                if (Number(error.status) === 402 || /次数已用完|卡密已过期/.test(String(error.message || ''))) {
                    showPurchaseNotice(true);
                }
                console.warn('[' + extensionName + '] automatic generation error (' + (reason || 'poll') + ')', error);
            } finally {
                autoGenerateInFlight.delete(inFlightKey);
            }
        } finally {
            autoGeneratePollingBusy = false;
        }
    }

    function showToast(type, message) {
        if (window.toastr && window.toastr[type]) {
            window.toastr[type](message, '默默画图');
        } else {
            console[type === 'error' ? 'error' : 'log'](message);
        }
    }

    function parseManifestVersion(content) {
        try {
            return String(JSON.parse(content).version || '0.0.0').trim();
        } catch (error) {
            throw new Error('版本文件格式错误');
        }
    }

    function compareVersions(left, right) {
        var leftParts = String(left || '0.0.0').replace(/^v/i, '').split('.').map(Number);
        var rightParts = String(right || '0.0.0').replace(/^v/i, '').split('.').map(Number);
        var length = Math.max(leftParts.length, rightParts.length);
        for (var index = 0; index < length; index++) {
            var leftValue = Number.isFinite(leftParts[index]) ? leftParts[index] : 0;
            var rightValue = Number.isFinite(rightParts[index]) ? rightParts[index] : 0;
            if (leftValue > rightValue) return 1;
            if (leftValue < rightValue) return -1;
        }
        return 0;
    }

    async function fetchRemoteUpdaterFile(filePath) {
        var url = 'https://raw.githubusercontent.com/' + updaterRepoOwner + '/' + updaterRepoName + '/main/' + filePath + '?t=' + Date.now();
        var response = await fetch(url, { cache: 'no-store' });
        if (!response.ok) throw new Error('GitHub 返回 HTTP ' + response.status);
        return response.text();
    }

    function renderUpdateState(message) {
        $('#cpab-current-version').text(updaterState.currentVersion);
        $('#cpab-update-status').text(message || '');
        $('#cpab-settings .cpab-update-panel').toggleClass('has-update', updaterState.available);
        var $button = $('#cpab-check-update');
        if (updaterState.updating) {
            $button.prop('disabled', true).html('<i class="fa-solid fa-spinner fa-spin"></i> 正在更新...');
        } else if (updaterState.checking) {
            $button.prop('disabled', true).html('<i class="fa-solid fa-spinner fa-spin"></i> 检查中...');
        } else if (updaterState.available) {
            $button.prop('disabled', false).html('<i class="fa-solid fa-cloud-arrow-down"></i> 立即更新 v' + updaterState.latestVersion);
        } else {
            $button.prop('disabled', false).html('<i class="fa-solid fa-cloud-arrow-down"></i> 检查更新');
        }
    }

    function showAutomaticUpdateNotice() {
        if (!updaterState.available || updaterState.notifiedVersion === updaterState.latestVersion) return;
        updaterState.notifiedVersion = updaterState.latestVersion;
        var message = '发现新版本 v' + updaterState.latestVersion + '，请打开“默默画图”设置，点击“立即更新”。';
        if (window.toastr && window.toastr.warning) {
            window.toastr.warning(message, '默默画图有更新', {
                closeButton: true,
                timeOut: 0,
                extendedTimeOut: 0
            });
        } else {
            window.alert(message);
        }
    }

    async function checkForUpdates(isManual) {
        if (updaterState.checking || updaterState.updating) return;
        updaterState.checking = true;
        renderUpdateState('正在检查 GitHub 新版本...');
        try {
            var localResponse = await fetch(extensionFolderPath + '/manifest.json?t=' + Date.now(), { cache: 'no-store' });
            if (!localResponse.ok) throw new Error('本地版本读取失败，HTTP ' + localResponse.status);
            updaterState.currentVersion = parseManifestVersion(await localResponse.text());
            updaterState.latestVersion = parseManifestVersion(await fetchRemoteUpdaterFile('manifest.json'));
            updaterState.available = compareVersions(updaterState.latestVersion, updaterState.currentVersion) > 0;
            if (updaterState.available) {
                renderUpdateState('发现新版本 v' + updaterState.latestVersion + '，点击按钮即可更新并自动刷新。');
                showAutomaticUpdateNotice();
                if (isManual) showToast('success', '发现新版本 v' + updaterState.latestVersion + '，请点击立即更新');
            } else {
                renderUpdateState('当前已是最新版本 v' + updaterState.currentVersion);
                if (isManual) showToast('success', '当前已是最新版本 v' + updaterState.currentVersion);
            }
        } catch (error) {
            renderUpdateState('检查更新失败，可稍后点击重试：' + (error.message || error));
            if (isManual) showToast('error', '检查更新失败：' + (error.message || error));
            else console.warn('[' + extensionName + '] automatic update check failed', error);
        } finally {
            updaterState.checking = false;
            renderUpdateState($('#cpab-update-status').text());
        }
    }

    async function performExtensionUpdate() {
        if (updaterState.updating) return;
        updaterState.updating = true;
        renderUpdateState('正在下载并安装新版本，请不要关闭页面...');
        try {
            var context = contextGetter();
            var common = context && context.common ? context.common : context;
            var extensions = context && context.extensions ? context.extensions : {};
            var getRequestHeaders = common && common.getRequestHeaders;
            var extensionTypes = extensions && extensions.extension_types ? extensions.extension_types : (window.extension_types || {});
            if (typeof getRequestHeaders !== 'function') throw new Error('当前酒馆版本未提供扩展更新接口');
            var response = await fetch('/api/extensions/update', {
                method: 'POST',
                headers: getRequestHeaders(),
                body: JSON.stringify({
                    extensionName: extensionName,
                    global: extensionTypes[extensionName] === 'global'
                })
            });
            if (!response.ok) throw new Error((await response.text()) || ('HTTP ' + response.status));
            renderUpdateState('更新成功，即将自动刷新页面...');
            showToast('success', '默默画图更新成功，页面即将刷新');
            setTimeout(function () { window.location.reload(); }, 2200);
        } catch (error) {
            updaterState.updating = false;
            renderUpdateState('更新失败：' + (error.message || error));
            showToast('error', '更新失败：' + (error.message || error));
        }
    }

    function setStatus(text) {
        $('#cpab-status').text(String(text || ''));
    }

    function purchaseMessage() {
        return '免费额度已用完，请加QQ群联系群主获得更多额度。\n\n5元：500次\n10元：1200次\n20元：包月不限额\n\nQQ群1：118774271\nQQ群2：705941358';
    }

    function showPurchaseNotice(force) {
        if (purchaseNoticeShown && !force) return;
        purchaseNoticeShown = true;
        var message = purchaseMessage();
        if (window.toastr && window.toastr.warning) {
            window.toastr.warning(message.replace(/\n/g, '<br>'), '额度已用完', {
                closeButton: true,
                timeOut: 0,
                extendedTimeOut: 0,
                escapeHtml: false
            });
        } else {
            window.alert(message);
        }
    }

    function handleQuotaNotice(quota) {
        if (quota && quota.plan_type === 'credits' && Number(quota.remaining) <= 0) {
            showPurchaseNotice(false);
        } else if (quota && (quota.plan_type !== 'credits' || Number(quota.remaining) > 0)) {
            purchaseNoticeShown = false;
        }
    }
    function showTrialAlreadyClaimedNotice() {
        var message = '本机已经领取过免费50次额度，需要更多额度请联系群主购买。\n\n5元：500次\n10元：1200次\n20元：包月不限额\n\nQQ群1：118774271\nQQ群2：705941358';
        if (window.toastr && window.toastr.warning) {
            window.toastr.warning(message.replace(/\n/g, '<br>'), '免费额度已经领取', {
                closeButton: true,
                timeOut: 0,
                extendedTimeOut: 0,
                escapeHtml: false
            });
        } else {
            window.alert(message);
        }
    }


    function saveSettings() {
        settings.resolution = normalizeResolution(settings.resolution);
        settings.steps = normalizeSteps(settings.steps);
        Object.assign(extensionSettingsRoot[extensionName], settings);
        localStorage.setItem(storageKey, JSON.stringify(settings));
        if (typeof window.saveSettingsDebounced === 'function') window.saveSettingsDebounced();
    }

    function normalizeApiUrl(value) {
        return String(value || '').trim().replace(/\/+$/, '');
    }


    async function refreshDiscoveredApiUrl(force, silent) {
        var now = Date.now();
        if (!force && normalizeApiUrl(settings.apiUrl) && now - lastEndpointDiscoveryAt < endpointDiscoveryIntervalMs) {
            return normalizeApiUrl(settings.apiUrl);
        }
        if (endpointDiscoveryPromise) return endpointDiscoveryPromise;
        endpointDiscoveryPromise = (async function () {
            var response;
            try {
                response = await fetch(endpointDiscoveryUrl + '?t=' + Date.now(), { method: 'GET', cache: 'no-store' });
            } catch (error) {
                if (!silent) showToast('error', '无法查询最新服务器地址：' + (error.message || error));
                throw new Error('无法查询最新服务器地址');
            }
            var data;
            try { data = await response.json(); }
            catch (error) { throw new Error('服务器地址公告返回格式错误'); }
            if (!response.ok || !data || data.ok === false || !data.api_url) {
                throw new Error((data && data.error) || '服务器地址公告暂不可用');
            }
            var discovered = normalizeApiUrl(data.api_url);
            if (!/^https:\/\/[a-z0-9-]+\.trycloudflare\.com$/i.test(discovered)) {
                throw new Error('服务器地址公告中的网址无效');
            }
            var changed = discovered !== normalizeApiUrl(settings.apiUrl);
            settings.apiUrl = discovered;
            lastEndpointDiscoveryAt = Date.now();
            saveSettings();
            $('#cpab-api-url').val(discovered);
            if (changed && !silent) showToast('success', '已自动获取最新画图服务器地址');
            return discovered;
        })();
        try { return await endpointDiscoveryPromise; }
        finally { endpointDiscoveryPromise = null; }
    }

    function requireApiUrl() {
        var apiUrl = normalizeApiUrl(settings.apiUrl);
        if (!apiUrl) throw new Error('请先填写网址');
        if (!/^https?:\/\//i.test(apiUrl)) throw new Error('网址必须以 http:// 或 https:// 开头');
        return apiUrl;
    }

    function createInstallId() {
        if (window.crypto && typeof window.crypto.randomUUID === 'function') {
            return window.crypto.randomUUID().replace(/-/g, '');
        }
        if (window.crypto && typeof window.crypto.getRandomValues === 'function') {
            var bytes = new Uint8Array(24);
            window.crypto.getRandomValues(bytes);
            return Array.from(bytes).map(function (value) { return value.toString(16).padStart(2, '0'); }).join('');
        }
        return 'install_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);
    }

    function ensureInstallId() {
        var installId = String(settings.installId || '').trim();
        if (!/^[A-Za-z0-9_-]{16,128}$/.test(installId)) {
            installId = createInstallId();
            settings.installId = installId;
            saveSettings();
        }
        return installId;
    }

    async function claimTrialKey(apiUrl, silent) {
        if (trialClaimPromise) return trialClaimPromise;
        trialClaimPromise = (async function () {
            setStatus('正在领取新用户50次免费额度...');
            var response;
            try {
                response = await fetch(apiUrl + '/v1/trial', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ install_id: ensureInstallId() })
                });
            } catch (error) {
                throw new Error('无法领取免费额度：' + (error.message || error));
            }
            var data;
            try { data = await response.json(); }
            catch (error) { throw new Error('免费额度接口返回的不是 JSON，HTTP ' + response.status); }
            if (!response.ok || !data || data.ok === false || !data.api_key) {
                var claimError = new Error((data && data.error) || ('免费额度领取失败，HTTP ' + response.status));
                claimError.status = response.status;
                claimError.payload = data;
                throw claimError;
            }
            if (!data.created) {
                setStatus('本机已经领取过免费50次额度');
                if (!silent) showTrialAlreadyClaimedNotice();
                return data;
            }
            settings.apiKey = String(data.api_key);
            saveSettings();
            $('#cpab-api-key').val(settings.apiKey);
            setStatus('已领取新用户50次免费额度，可以直接画图');
            if (!silent) showToast('success', '免费50次额度领取成功，卡密已自动填写');
            return data;
        })();
        try { return await trialClaimPromise; }
        finally { trialClaimPromise = null; }
    }

    async function requireConnectionSettings() {
        await refreshDiscoveredApiUrl(false, true);
        var apiUrl = requireApiUrl();
        var apiKey = String(settings.apiKey || '').trim();
        if (!apiKey) throw new Error('请先点击“领取免费50次”；免费额度用完后，请加QQ群联系群主购买卡密');
        return { apiUrl: apiUrl, apiKey: apiKey };
    }

    async function apiRequest(path, options) {
        var connection = await requireConnectionSettings();
        var requestOptions = Object.assign({}, options || {});
        requestOptions.headers = Object.assign({
            'X-API-Key': connection.apiKey,
            'Content-Type': 'application/json'
        }, requestOptions.headers || {});
        var response;
        try {
            response = await fetch(connection.apiUrl + path, requestOptions);
        } catch (error) {
            var previousUrl = connection.apiUrl;
            try {
                var latestUrl = await refreshDiscoveredApiUrl(true, true);
                if (latestUrl && latestUrl !== previousUrl) {
                    connection.apiUrl = latestUrl;
                    response = await fetch(connection.apiUrl + path, requestOptions);
                }
            } catch (discoveryError) {
                console.warn('[' + extensionName + '] endpoint rediscovery failed', discoveryError);
            }
            if (!response) throw new Error('无法连接服务器：' + (error.message || error));
        }
        var data;
        try {
            data = await response.json();
        } catch (error) {
            throw new Error('API 返回的不是 JSON，HTTP ' + response.status);
        }
        if (!response.ok || !data || data.ok === false) {
            var apiError = new Error((data && data.error) || ('API 请求失败，HTTP ' + response.status));
            apiError.status = response.status;
            apiError.payload = data;
            throw apiError;
        }
        return data;
    }

    function formatDate(value) {
        if (!value) return '—';
        var date = new Date(value);
        return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleString('zh-CN', { hour12: false });
    }

    function formatQuota(quota) {
        if (!quota) return '额度数据为空';
        var name = quota.name ? '【' + quota.name + '】 ' : '';
        if (quota.plan_type === 'credits') {
            return name + '次数卡：剩余 ' + quota.remaining + ' / ' + quota.total + ' 次，已使用 ' + quota.used + ' 次';
        }
        if (!quota.activated) {
            return name + '时长卡：未激活；首次成功出图后开始计算 ' + quota.duration_days + ' 天';
        }
        return name + '时长卡：剩余约 ' + quota.days_remaining + ' 天；到期时间 ' + formatDate(quota.expires_at);
    }

    async function refreshQuota(silent) {
        var $quota = $('#cpab-quota');
        $quota.removeClass('is-ok is-error').addClass('is-idle').text('正在查询额度...');
        try {
            var data = await apiRequest('/v1/quota', { method: 'GET' });
            $quota.removeClass('is-idle is-error').addClass('is-ok').text(formatQuota(data.quota));
            handleQuotaNotice(data.quota);
            return data.quota;
        } catch (error) {
            $quota.removeClass('is-idle is-ok').addClass('is-error').text(error.message || String(error));
            if (!silent) showToast('error', error.message || String(error));
            throw error;
        }
    }

    function queueText() {
        return queueState === 'offline' ? '队列离线' : '前方 ' + lastQueueAhead;
    }

    function updateQueueBadges() {
        var stateClass = queueState === 'offline' ? 'is-offline' : (lastQueueAhead > 0 ? 'is-busy' : 'is-idle');
        var text = queueText();
        $('.cpab-queue-badge').removeClass('is-idle is-busy is-offline').addClass(stateClass).text(text);
        $('#cpab-queue-status').removeClass('is-idle is-busy is-offline').addClass(stateClass).text('服务器队列：' + text);
    }

    async function refreshQueueStatus(silent) {
        if (queuePollBusy) return;
        if (!normalizeApiUrl(settings.apiUrl) || !String(settings.apiKey || '').trim()) {
            queueState = 'offline';
            updateQueueBadges();
            return;
        }
        queuePollBusy = true;
        try {
            var data = await apiRequest('/v1/status', { method: 'GET' });
            lastQueueAhead = Math.max(0, Number(data.queue && data.queue.ahead) || 0);
            queueState = 'online';
            updateQueueBadges();
        } catch (error) {
            queueState = 'offline';
            updateQueueBadges();
            if (!silent) showToast('error', error.message || String(error));
        } finally {
            queuePollBusy = false;
        }
    }

    function cleanPrompt(value) {
        var prompt = String(value || '');
        prompt = prompt.replace(/<br\s*\/?\s*>/gi, '\n');
        prompt = prompt.replace(/<\/?p(?:\s[^>]*)?>/gi, '\n');
        prompt = prompt.replace(/<\/?(?:details|summary)(?:\s[^>]*)?>/gi, '');
        prompt = $('<textarea>').html(prompt).text();
        prompt = prompt.replace(/^\s*(?:\x60{3}[a-z0-9_-]*\s*)?/i, '');
        prompt = prompt.replace(/\s*\x60{3}\s*$/i, '');
        return prompt.trim();
    }

    function extractImagePrompt(messageText) {
        var text = String(messageText || '').trim();
        if (!text) throw new Error('消息内容为空，无法提取提示词');
        var patterns = [
            /\[ImagePrompt\|([\s\S]*?)\](?![\s\S]*\[ImagePrompt\|)/i,
            /<ImagePrompt(?:\s[^>]*)?>([\s\S]*?)<\/ImagePrompt>/i,
            /<image_prompt(?:\s[^>]*)?>([\s\S]*?)<\/image_prompt>/i,
            /<details(?:\s[^>]*)?>[\s\S]*?<summary(?:\s[^>]*)?>\s*(?:绘画|绘图|出图|图片|Image)\s*提示词\s*<\/summary>([\s\S]*?)<\/details>/i,
            /【\s*(?:绘画|绘图|出图|图片)\s*提示词\s*】\s*([\s\S]*?)(?=\n\s*【|$)/i,
            /(?:^|\n)\s*(?:#{1,6}\s*)?(?:绘画|绘图|出图|图片)\s*提示词\s*[：:]\s*([\s\S]*?)(?=\n\s*(?:#{1,6}\s*)?(?:负面提示词|Negative\s*Prompt|正文|说明)\s*[：:]|$)/i
        ];
        for (var i = 0; i < patterns.length; i++) {
            var match = text.match(patterns[i]);
            var prompt = match && cleanPrompt(match[1]);
            if (prompt) return prompt;
        }
        throw new Error('没有识别到绘画提示词');
    }

    function messageHasPrompt(message) {
        if (!message || message.is_user || !message.mes) return false;
        try {
            return !!extractImagePrompt(message.mes);
        } catch (error) {
            return false;
        }
    }

    function getButtonContainer($mes) {
        var $container = $mes.find('.cpab-bottom-buttons').first();
        if ($container.length) return $container;
        var $text = $mes.find('.mes_text').first();
        if ($text.length) {
            $container = $('<div class="cpab-bottom-buttons"></div>');
            $text.after($container);
            return $container;
        }
        var $block = $mes.find('.mes_block').first();
        if ($block.length) {
            $container = $('<div class="cpab-bottom-buttons"></div>');
            $block.append($container);
            return $container;
        }
        return $mes.find('.extraMesButtons').first().length ? $mes.find('.extraMesButtons').first() : $mes.find('.mes_buttons').first();
    }

    function ensureButtonForMessage(messageId) {
        var context = contextGetter();
        var message = context && context.chat ? context.chat[messageId] : null;
        var $mes = $('.mes[mesid="' + messageId + '"]');
        if (!$mes.length) return;
        if (!messageHasPrompt(message)) {
            $mes.find('.cpab-bottom-buttons').remove();
            return;
        }
        var $target = getButtonContainer($mes);
        if (!$target.length) return;
        if (!$target.find('.cpab-mes-button').length) {
            $target.append('<div class="mes_button cpab-mes-button" role="button" tabindex="0" title="生成图片"><i class="fa-solid fa-image"></i></div>');
        }
        if (!$target.find('.cpab-random-button').length) {
            $target.append('<div class="mes_button cpab-random-button" role="button" tabindex="0" title="随机重绘"><i class="fa-solid fa-rotate"></i></div>');
        }
        if (!$target.find('.cpab-optimize-button').length) {
            $target.append('<div class="mes_button cpab-optimize-button" role="button" tabindex="0" title="固定种子，步数 +2 优化（最高 8 步）"><i class="fa-solid fa-wand-magic-sparkles"></i></div>');
        }
        if (!$target.find('.cpab-queue-badge').length) {
            $target.append('<span class="cpab-queue-badge" title="当前提交任务前预计需要等待的任务数"></span>');
        }
        $target.find('.cpab-mes-button, .cpab-random-button, .cpab-optimize-button').attr('data-cpab-mesid', String(messageId));
        updateQueueBadges();
    }

    function refreshButtons() {
        var context = contextGetter();
        var chat = context && context.chat ? context.chat : [];
        chat.forEach(function (_, index) { ensureButtonForMessage(index); });
    }

    function setButtonState($button, state, title) {
        if (!$button || !$button.length) return;
        $button.removeClass('is-loading is-success is-error');
        if (state) $button.addClass(state);
        if (title) $button.attr('title', title);
    }

    function getGenerationMeta(messageId) {
        var context = contextGetter();
        var message = context && context.chat ? context.chat[messageId] : null;
        var meta = message && message.extra ? message.extra.cpab_last_generation : null;
        return meta && typeof meta === 'object' ? meta : null;
    }

    async function uploadImage(base64Data, format) {
        var context = contextGetter();
        var characterName = String((context && (context.name2 || context.characterName)) || 'ComfyUI-Public').trim();
        var payload = {
            image: base64Data,
            format: format || 'png',
            ch_name: characterName || 'ComfyUI-Public',
            filename: 'public_api_' + Date.now()
        };
        var data;
        try {
            data = await $.ajax({
                url: '/api/images/upload',
                method: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(payload)
            });
        } catch (error) {
            var details = error && (error.responseJSON || error.responseText || error.statusText);
            throw new Error('图片保存到酒馆失败：' + (typeof details === 'string' ? details : JSON.stringify(details || error)));
        }
        if (!data || !data.path) throw new Error('酒馆没有返回图片保存路径');
        return data.path;
    }

    async function emitMessageUpdated(messageId) {
        var eventSource = window.eventSource || (window.SillyTavern && window.SillyTavern.eventSource);
        var eventTypes = window.event_types || (window.SillyTavern && window.SillyTavern.event_types) || {};
        if (eventSource && eventSource.emit && eventTypes.MESSAGE_UPDATED) {
            await eventSource.emit(eventTypes.MESSAGE_UPDATED, Number(messageId));
        }
    }

    async function saveChatSafe() {
        var context = contextGetter();
        if (context && typeof context.saveChat === 'function') {
            await context.saveChat();
        }
    }

    function delay(ms) {
        return new Promise(function (resolve) { setTimeout(resolve, ms); });
    }

    async function forceSaveViaOfficialEditor(messageId, messageText) {
        var scrollContainer = document.querySelector('#chat');
        var previousScrollTop = scrollContainer ? scrollContainer.scrollTop : null;
        var $messageBlock = $('#chat .mes[mesid="' + messageId + '"]');
        if (!$messageBlock.length) return false;

        var $editButton = $messageBlock.find('.mes_edit').first();
        if (!$editButton.length) return false;
        $editButton.trigger('click');
        await delay(60);

        var $textarea = $messageBlock.find('.edit_textarea:visible').first();
        if (!$textarea.length) return false;
        $textarea.val(String(messageText || ''));
        var textareaElement = $textarea.get(0);
        if (textareaElement) {
            textareaElement.dispatchEvent(new Event('input', { bubbles: true }));
            textareaElement.dispatchEvent(new Event('change', { bubbles: true }));
        }

        await delay(60);
        var $doneButton = $messageBlock.find('.mes_edit_done:visible').first();
        if (!$doneButton.length) return false;
        $doneButton.trigger('click');
        await delay(150);

        if (scrollContainer && previousScrollTop !== null) {
            scrollContainer.scrollTop = previousScrollTop;
        }
        return true;
    }

    async function injectImage(messageId, imageUrl, prompt, quota, generationMeta) {
        var context = contextGetter();
        var message = context && context.chat ? context.chat[messageId] : null;
        if (!message) throw new Error('找不到目标楼层');
        message.extra = message.extra || {};
        message.extra.media = Array.isArray(message.extra.media) ? message.extra.media : [];
        message.extra.media.push({ url: imageUrl, title: prompt, type: 'image', source: 'generated' });
        message.extra.media_index = message.extra.media.length - 1;
        message.extra.inline_image = true;
        message.extra.image = imageUrl;
        message.extra.cpab_last_prompt = prompt;
        message.extra.cpab_last_quota = quota || null;
        message.extra.cpab_last_generation = generationMeta;
        var scenePrompt = generationMeta && generationMeta.scenePrompt ? generationMeta.scenePrompt : prompt;
        message.extra.cpab_auto_generated_prompt = scenePrompt;
        markMessageGenerated(messageId, scenePrompt);

        if (
            Array.isArray(message.swipes)
            && typeof message.swipe_id === 'number'
            && message.swipes[message.swipe_id] !== undefined
        ) {
            message.swipes[message.swipe_id] = message.mes;
        }

        await saveChatSafe();
        await emitMessageUpdated(messageId);
        var editorRefreshed = await forceSaveViaOfficialEditor(messageId, message.mes);
        if (!editorRefreshed) {
            await emitMessageUpdated(messageId);
        }
        refreshButtons();
    }

    function readGenerationOptions() {
        var parts = normalizeResolution(settings.resolution).split('x');
        return { width: Number(parts[0]), height: Number(parts[1]), steps: normalizeSteps(settings.steps) };
    }

    function buildGenerationRequest(messageId, mode) {
        var options = readGenerationOptions();
        var last = getGenerationMeta(messageId);
        var payload = { width: options.width, height: options.height, steps: options.steps };
        var actionLabel = '生成图片';
        if (mode === 'random') {
            payload.steps = last && allowedSteps.indexOf(Number(last.steps)) >= 0 ? Number(last.steps) : options.steps;
            actionLabel = '随机重绘';
        }
        if (mode === 'optimize') {
            if (!last) throw new Error('这层还没有历史图片，请先点一次生成图片或随机重绘');
            if (!Number.isFinite(Number(last.seed))) throw new Error('找不到上一次生成的 seed');
            if (!Number.isFinite(Number(last.steps))) throw new Error('找不到上一次生成的步数');
            payload.seed = Number(last.seed);
            payload.steps = Math.min(8, Number(last.steps) + 2);
            actionLabel = '固定 seed 优化（' + last.steps + ' → ' + payload.steps + ' 步）';
        }
        return { payload: payload, actionLabel: actionLabel };
    }

    async function generateForMessage(messageId, $button, mode) {
        var context = contextGetter();
        var message = context && context.chat ? context.chat[messageId] : null;
        if (!message) throw new Error('找不到对应楼层消息');
        var scenePrompt = extractImagePrompt(message.mes);
        var selectedStyle = getStylePreset(settings.stylePreset);
        var selectedStyleUi = getStylePresetUi(selectedStyle.id);
        var prompt = buildStyledPrompt(scenePrompt, selectedStyle.id);
        var request = buildGenerationRequest(messageId, mode || 'normal');
        request.payload.prompt = prompt;
        setButtonState($button, 'is-loading', request.actionLabel + '中');
        await refreshQueueStatus(true);
        setStatus('楼层 ' + messageId + '：' + request.actionLabel + '，服务器前方 ' + lastQueueAhead + ' 个任务');
        try {
            var data = await apiRequest('/v1/generate', { method: 'POST', body: JSON.stringify(request.payload) });
            setStatus('出图完成，正在保存到酒馆...');
            var imageUrl = await uploadImage(data.data, data.format || 'png');
            var generationMeta = {
                seed: Number(data.seed),
                steps: Number(data.steps),
                prompt: prompt,
                scenePrompt: scenePrompt,
                stylePreset: selectedStyle.id,
                styleName: selectedStyleUi.label,
                styleEnglishName: selectedStyle.name,
                imageUrl: imageUrl,
                savedAt: Date.now()
            };
            await injectImage(messageId, imageUrl, prompt, data.quota, generationMeta);
            $('#cpab-quota').removeClass('is-idle is-error').addClass('is-ok').text(formatQuota(data.quota));
            handleQuotaNotice(data.quota);
            setButtonState($button, 'is-success', '出图成功，点击可再次生成');
            setStatus('楼层 ' + messageId + '：出图完成，seed=' + data.seed + '，steps=' + data.steps);
            showToast('success', '图片已注入楼层，' + formatQuota(data.quota));
            setTimeout(function () {
                setButtonState($button, '', mode === 'random' ? '随机重绘' : (mode === 'optimize' ? '固定种子，步数 +2 优化（最高 8 步）' : '生成图片'));
            }, 2500);
        } finally {
            refreshQueueStatus(true).catch(function () {});
        }
    }

    async function handleGenerateClick(event, mode) {
        event.preventDefault();
        event.stopPropagation();
        var $button = $(event.currentTarget);
        var messageId = Number($button.attr('data-cpab-mesid'));
        try {
            await generateForMessage(messageId, $button, mode);
        } catch (error) {
            setButtonState($button, 'is-error', '生图失败，点击重试');
            setStatus('生图失败：' + (error.message || error));
            showToast('error', error.message || String(error));
            if (Number(error.status) === 402 || /次数已用完|卡密已过期/.test(String(error.message || ''))) showPurchaseNotice(true);
            refreshQuota(true).catch(function () {});
            refreshQueueStatus(true).catch(function () {});
        }
    }

    function loadSettingsToUi() {
        $('#cpab-api-url').val(settings.apiUrl || '');
        $('#cpab-api-key').val(settings.apiKey || '');
        $('#cpab-resolution').val(normalizeResolution(settings.resolution));
        $('#cpab-steps').val(String(normalizeSteps(settings.steps)));
        $('#cpab-auto-generate').prop('checked', Boolean(settings.autoGenerate));
        renderStylePresetSelect();
        updateQueueBadges();
    }

    function renderStylePresetSelect() {
        var selected = getStylePreset(settings.stylePreset);
        var selectedUi = getStylePresetUi(selected.id);
        var $select = $('#cpab-style-select');
        if (!$select.length) return;
        $select.empty();
        var groups = {};
        stylePresets.forEach(function (preset) {
            var ui = getStylePresetUi(preset.id);
            if (!groups[ui.group]) {
                groups[ui.group] = $('<optgroup></optgroup>').attr('label', ui.group);
                $select.append(groups[ui.group]);
            }
            groups[ui.group].append($('<option></option>').val(preset.id).text(ui.label));
        });
        $select.val(selected.id);
        $('#cpab-style-current').text('当前风格：' + selectedUi.label);
        $('#cpab-style-description').text(selectedUi.description);
    }

    function collectSettingsFromUi() {
        settings.apiUrl = normalizeApiUrl($('#cpab-api-url').val());
        settings.apiKey = String($('#cpab-api-key').val() || '').trim();
        settings.resolution = normalizeResolution($('#cpab-resolution').val());
        settings.steps = normalizeSteps($('#cpab-steps').val());
        settings.autoGenerate = $('#cpab-auto-generate').is(':checked');
        settings.stylePreset = normalizeStylePreset(settings.stylePreset);
    }

    function bindSettingsEvents() {
        $('#cpab-style-select').on('change', function () {
            settings.stylePreset = normalizeStylePreset($(this).val());
            saveSettings();
            renderStylePresetSelect();
            var selectedUi = getStylePresetUi(settings.stylePreset);
            setStatus('画风已切换为“' + selectedUi.label + '”，下次生图自动使用');
            showToast('success', '已选择画风：' + selectedUi.label);
        });
        $('#cpab-check-update').on('click', function () {
            if (updaterState.available) performExtensionUpdate();
            else checkForUpdates(true);
        });
        $('#cpab-save').on('click', async function () {
            collectSettingsFromUi();
            saveSettings();
            refreshButtons();
            if (settings.autoGenerate) scheduleAutoGenerate('SETTINGS_SAVED');
            try {
                if (settings.apiKey) await Promise.all([refreshQuota(true), refreshQueueStatus(true)]);
                setStatus(settings.apiKey ? '设置已保存' : '设置已保存，请点击领取免费50次；用完后加QQ群联系群主购买卡密');
                showToast('success', '默默画图设置已保存');
            } catch (error) {
                setStatus('保存后连接失败：' + (error.message || error));
                showToast('error', error.message || String(error));
            }
        });
        $('#cpab-claim-trial').on('click', async function () {
            var $button = $(this);
            var currentKey = String($('#cpab-api-key').val() || settings.apiKey || '').trim();
            if (/^trial_/i.test(currentKey)) {
                showTrialAlreadyClaimedNotice();
                setStatus('本机已经领取过免费50次额度');
                return;
            }
            if (currentKey) {
                showToast('warning', '当前已有购买卡密，不会用免费卡覆盖');
                return;
            }
            $button.prop('disabled', true).addClass('is-loading');
            try {
                await refreshDiscoveredApiUrl(true, true);
                var data = await claimTrialKey(requireApiUrl(), false);
                if (data && data.created) {
                    await Promise.all([refreshQuota(true), refreshQueueStatus(true)]);
                }
            } catch (error) {
                setStatus('免费额度领取失败：' + (error.message || error));
                showToast('error', error.message || String(error));
                if (Number(error.status) === 429) showTrialAlreadyClaimedNotice();
            } finally {
                $button.prop('disabled', false).removeClass('is-loading');
            }
        });
        $('#cpab-check-quota').on('click', async function () {
            collectSettingsFromUi();
            saveSettings();
            try {
                await Promise.all([refreshQuota(false), refreshQueueStatus(false)]);
                setStatus('额度和服务器队列查询成功');
            } catch (error) {
                setStatus('查询失败：' + (error.message || error));
            }
        });
        $('#cpab-toggle-key').on('click', function () {
            var $key = $('#cpab-api-key');
            var visible = $key.attr('type') === 'text';
            $key.attr('type', visible ? 'password' : 'text');
            $(this).find('i').toggleClass('fa-eye', visible).toggleClass('fa-eye-slash', !visible);
        });
    }

    function bindGlobalEvents() {
        $(document).off('click.cpabGenerate').on('click.cpabGenerate', '.cpab-mes-button', function (event) { handleGenerateClick(event, 'normal'); });
        $(document).off('click.cpabRandom').on('click.cpabRandom', '.cpab-random-button', function (event) { handleGenerateClick(event, 'random'); });
        $(document).off('click.cpabOptimize').on('click.cpabOptimize', '.cpab-optimize-button', function (event) { handleGenerateClick(event, 'optimize'); });
        var eventSource = window.eventSource || (window.SillyTavern && window.SillyTavern.eventSource);
        var eventTypes = window.event_types || (window.SillyTavern && window.SillyTavern.event_types) || {};
        if (eventSource && eventSource.on) {
            if (eventTypes.CHARACTER_MESSAGE_RENDERED) eventSource.on(eventTypes.CHARACTER_MESSAGE_RENDERED, function (messageId) {
                ensureButtonForMessage(messageId);
                scheduleAutoGenerate('CHARACTER_MESSAGE_RENDERED');
            });
            if (eventTypes.CHAT_CHANGED) eventSource.on(eventTypes.CHAT_CHANGED, function () {
                refreshButtons();
                scheduleAutoGenerate('CHAT_CHANGED');
            });
            if (eventTypes.MESSAGE_SWIPED) eventSource.on(eventTypes.MESSAGE_SWIPED, function () {
                refreshButtons();
                scheduleAutoGenerate('MESSAGE_SWIPED');
            });
            if (eventTypes.MESSAGE_UPDATED) eventSource.on(eventTypes.MESSAGE_UPDATED, function () {
                refreshButtons();
                scheduleAutoGenerate('MESSAGE_UPDATED');
            });
            if (eventTypes.MESSAGE_DELETED) eventSource.on(eventTypes.MESSAGE_DELETED, refreshButtons);
        }
        setInterval(refreshButtons, 3000);
        setInterval(function () { refreshQueueStatus(true).catch(function () {}); }, 2000);
        setInterval(function () {
            if (settings.autoGenerate) checkAutoGenerate('POLLING_INTERVAL').catch(function () {});
        }, 2000);
    }

    try {
        var settingsHtml = await $.get(extensionFolderPath + '/settings.html');
        $('#extensions_settings2').append(settingsHtml);
        loadSettingsToUi();
        bindSettingsEvents();
        bindGlobalEvents();
        refreshButtons();
        scheduleAutoGenerate('INIT');
        setTimeout(function () { checkForUpdates(false); }, 1800);
        try {
            await refreshDiscoveredApiUrl(true, false);
        } catch (error) {
            setStatus('最新地址获取失败，将尝试已保存地址：' + (error.message || error));
        }
        if (settings.apiUrl && settings.apiKey) {
            try {
                await Promise.all([refreshQuota(true), refreshQueueStatus(true)]);
            } catch (error) {
                setStatus('卡密连接失败：' + (error.message || error));
            }
        } else {
            setStatus('请点击领取免费50次；免费额度用完后，请加QQ群联系群主购买卡密');
        }
        console.log('[' + extensionName + '] loaded');
    } catch (error) {
        console.error('[' + extensionName + '] init failed', error);
        showToast('error', '插件初始化失败：' + (error.message || error));
    }
});
